### ISSUE TITLE
How to bootstrap with custom StackName

### ISSUE THREAD

**Issue by pdkn** [aws-solutions/qnabot-on-aws#160]
When Creating a new QnA bot through AWS CloudFormation console it asks for a custom StackName. Can the same be achieved from Cl? i.e as a config.json param? or  `npm run bootstrap --stack-name MyCustomBotName`? Thanks

**Comment by pdkn** [comment]
I've got this working by using `npm run up -- -- --stack-name MyCustomStackName` is there a better way to do this?

**Comment by pdkn** [comment]
I've edited bin/launch.js to 
```
var stackName = options.stackName || config.stackName
var StackName= stackName ? stackName : name(stack,{inc:true})
```
and now can also add to config.json

```
{
  ...
  "devEmail": "dev@email.com",
  "namespace": "dev",
  "stackName": "CustomStackName"
}
```

if you think it's of any use can put in a pull request?

**Comment by bobpskier** [comment]
Pull request would be great and I can merge it in. Thanks!
