### ISSUE TITLE
Instantly starting elicit response on startup

### ISSUE THREAD

**Issue by Dudemanguy** [aws-solutions/qnabot-on-aws#186]
I've thought of some workarounds to sort of get this (need to do more testing though), but I was wondering if there was a cleaner way to do this.

The use case here is that the QnA bot asks a bunch of questions that the user must answer. The only problem with this workflow is that the user must manually trigger the first question in some way (by saying the right keyword) and then the bot responds and elicit response takes over and it goes on from there. Basically the goal here is to completely skip the user having to initialize the elicit response and to just have the bot instantly start the first question right on start up.

Instead of this (current workflow):
```
User: Begin
Bot: Hi, what is your name?
User: My name is Joe Smith.
(etc.)
```

I'd like this:
```
Bot: Hi, what is your name?
User: My name is Joe Smith.
(etc.)
```

The workaround I thought of involved editing the default startup message to ask the initial question and then adding some ugly code to deal specifically with the initial response (a pseudo-elicit response if you will) and direct it to the next question. I haven't implemented it yet, but it should at least work for what I'm doing. Not sure if there's currently a better and more generic way to handle this though.

**Comment by bobpskier** [comment]
I'm curious as to the client being used for the workflow.

If using aws-lex-web-ui (also project on github) as the client, there is an api provided on the Iframe loader which lets the parent page send initial text/question to the bot. You can achieve the desired result by calling this api after the lex web ui has fully loaded on the page. An event is generated to the parent page that indicates the lex web ui is fully loaded which would be the trigger to send in the initial question like 'Begin'. 

Thats where I would start first if possible. 

One problem with your approach is that the Bot does not see a new session until Lex receives a request first which would be the users first utterance. It might be conceivable to have a setting that is something like 'auto first question' and for a new session, ignore what the user initially says but instead provides the answer to the first question like 'Hi, before we get started, what is your name?' and starts down the path of asking questions.
