### ISSUE TITLE
Adding handlebars code invisibly to all answers

### ISSUE THREAD

**Issue by tommcgee57** [aws-solutions/qnabot-on-aws#219]
I'd like to add an automatic counter to our QnA bot, so that after users ask 7 questions, they get a message that they've reached their limit.

Something like this code probably could do what I need;:

```
{{#ifCond UserInfo.InteractionCount  '>' 6}}
  You have asked {{UserInfo.InteractionCount}} questions.
{{/ifCond}}
```
but I don't think copying-and-pasting this code into each and every question in the bot is the right way to do it. How would I apply this globally? I'd like to avoid a steep learning curve, I just want to add this one function!

**Comment by rstrahan** [comment]
Hi @tommcgee57  - Interesting.. I don't have a tidy answer for you right now, but this might be something we could improve.. Your options include:
1. adding the handlebars to every answer (just what you said you didn't want to do, and i can understand why!)
2. add a preprocesisng lambda function to implement this logic..
    The ability to add a preprocessing lambda is an 'undocumented feature'..  Create a new Lambda function - eg QNA-PreprocessFunction' just as though it were a Lambda Hook (ie it receives and returns an event object). Open the Fulfillment Lambda in the AWS Lambda console and set a new Lambda environment variable called `LAMBDA_PREPROCESS` to name of your new function. Now when each request is processed by the bot, it will call your new Lambda before doing moch else, and your new lambda can implement logic to check the req._userinfo.InteractionCount value in the event and if it exceeds your thershold, then modify req.question to point to a QiD that will return your count exceeded message. (Note: The code to call LAMBDA_PROPROCESS is in file /aws-ai-qna-bot/lambda/fulfillment/lib/middleware/2_preprocess.js)_
3. modify QnABot Source code to add support for configurable general purpose preprocessing logic that could be used for this kind of use case. Then send us a Pull Request, and we'll validate and include it in the next release. That would be a great feature to have.
4. wait for us to implement (3) in an upcoming release.. I'll add this to our backlog.. it would be a generally usefuly capability to have, but can't promise an ETA.

**Comment by tommcgee57** [comment]
Robert,

Thanks for your thoughtful reply. Permissions are one of the things that I always bang my head against the wall on when using AWS, and this might be another instance. When I create a new Lambda function, it asks for a role to base permissions on. I set it to the existing role for the fulfillment Lambda, then added the environmental variable as outlined in your message. The function code for the new Lambda is the one that comes right out of the box,

exports.handler = async (event) => {
    // TODO implement
    const response = {
        statusCode: 200,
        body: JSON.stringify('Hello from Lambda!'),
    };
    return response;
};

But now questions are responded to properly in the content designer screen, but the client URL only gives me “Sorry, I was unable to process your message. Try again later,” in response to the same questions. The CloudWatch logs showed one missing permission, which I added.

I know this it way outside the scope of your role here, so I don’t expect a solution. AWS permissions are Kryptonite.

Thanks again.

Tom

**Comment by tommcgee57** [comment]
Hm. Out of the box adding a generic Lambda function just broke the bot. It wasn’t able to process any questions.

I went back and removed the new environmental variable from the bot, but it still doesn’t understand the questions. It definitely did before!

Is there some rebuild step that’s necessary (other than the one in the content designer)?

TIA,

Tom

**Comment by tommcgee57** [comment]
Thomas A McGee would like to recall the message, "[aws-samples/aws-ai-qna-bot] Adding handlebars code invisibly to all answers (#219)".
