### ISSUE TITLE
Request Failed: error response from endpoint

### ISSUE THREAD

**Issue by tchnlgst** [aws-solutions/qnabot-on-aws#252]
When I deploy the CloudFormation stack, qna-bot works fine for a number of days, both the client and content designer.

A few days after deployment, I get the following error anytime I try to access the Content Designer & Admin back-end:
Request Failed: error response from endpoint

The client returns:
Unfortunately I encountered an error when searching for your answer. Please ask me again later.

What could be causing this? Where could I look?

**Comment by rstrahan** [comment]
Most likely related to issues related to Elasticsearch t2 instance types. Is the status of your Elasticsearch domain red? If you still see the problem please upgrade or reinstall with latest version to get the newer instance types.
