### ISSUE TITLE
Logs not saving in Elastic Search engine for QnA Bot chats

### ISSUE THREAD

**Issue by ABhishek278898** [aws-solutions/qnabot-on-aws#255]
We have developed QnA Bot using cloud formation template in which QnA bot chat logs should save in ES and Kibana platform will provide analytics and data visualization. We are not able to see any data for chat logs. (No metrics data saving)

We are using QnAFree Text chaining rule in QnA designer. Is this causing any issue while saving logs data in elastic search?

**Comment by rstrahan** [comment]
Sorry for delayed response. Are you still seeing the problem? If so, most common culprit is a change in the data types used in the request/response - eg session attributes that changed type, eg to a nested structure, without changing name. 
Check in the S3 'metrics' bucket for your QnABot stack for the error messages logged by kinesis firehouse.. if you see messages indicating incompatible schema for certain fields, that will be your clue.
Fixes include a) renaming the offending session attribute, b) reinstalling QnABot to allow metrics index to be recreated with the new structure
