### ISSUE TITLE
QnAbot vs Serverless Bot Framework

### ISSUE THREAD

**Issue by traverse-elastictier** [aws-solutions/qnabot-on-aws#265]
What is the difference between this and serverless bot framework? If one was to start building on either, what would is the more strategic, supported path by AWS? 

Serverless bot framework has a more "official" set of documentation and discoverability on AWS site, however QnAbot seems to be more active. 

https://github.com/awslabs/serverless-bot-framework/
https://aws.amazon.com/solutions/implementations/serverless-bot-framework/?did=sl_card&trk=sl_card

**Comment by rstrahan** [comment]
@traverse-elastictier Hi - great question! The answer is... it depends! 
The serverless bot framework solution is a good starting point if you are building your own transactional bot, say to provide self service workflows with different intents and multi-turn conversations to elicit slot values.. like ordering a product, booking an appointment, etc.  
Whereas the QnABot - this project - is ideal if your bot needs are focused mostly on Q&A use cases.. you can get get up and running fast without coding, but it also has extensibility and plenty of feature to not lock you in.  If you're not sure, watch this new video demo that covers many of the QnAbot features: https://www.youtube.com/watch?v=4Wxu775i5yM
_Without programming, the QnABot open source solution allows customers to quickly deploy self-service conversational AI on multiple channels including their contact centers and their web sites, also social media channels, SMS text messaging, or even Alexa skills. QnABot uses multiple AWS services including Amazon Lex, Amazon Kendra, Amazon Translate and more. Customers can configure curated answers to frequently asked questions using an integrated content management system supporting rich text and rich voice responses optimized for each channel, or they can expand the service’s answer knowledge base to include unstructured documents and PDFs, and existing web page content. The solution supports multiple languages with optional automatic translation of answers to the user’s local language. This video demonstrates many of these features and includes a bonus prototype demo of live agent transfer from the chat bot web UI_

We'll also be adding something like this soon to the serverless bot framework documentation to help answer your question as well.

> Question and Answer Bots
> Serverless Bot Framework allows for a quick implementation of an end to end chatbot solution with different functionalities listed above. If you want to implement a chatbot that is specialized in question and answer (Q&A) or frequently asked questions (FAQ), then refer to this blog post: Create a Question and Answer Bot with Amazon Lex and Amazon Alexa

**Comment by traverse-elastictier** [comment]
@rstrahan thank you for the response! Nice job on the video demo, that is how I discovered QnABot. What are the commercial use rights for QnABot? If its used as the basis of a commercial product, are there any legalese or use rights to be aware of?

**Comment by traverse-elastictier** [comment]
@rstrahan  -> Also, is there guidance for updating and patching serverless bot framework when operating in a production setting?

**Comment by rstrahan** [comment]
Hi @traverse-elastictier 

Re first question on commercial use rights for QnABot, see the licence file - https://github.com/aws-samples/aws-ai-qna-bot/blob/master/LICENSE.md

Re second question on serverless bot framework - please follow up on that via that project's site. 

Cheers
Bob
