### ISSUE TITLE
Elicit Response with connect adding default prompt after the elicit slot

### ISSUE THREAD

**Issue by jsenrag** [aws-solutions/qnabot-on-aws#268]
I'm implementing QnA Bot with Connect. I'm using Conditional Chaining and Elicit Response with a bot to get Campus Name. If Lex understands the name of the campus correctly then it works ok, but if not it prompts for the slot and then for a new question. Ex:

User: Parking Locations
QnA: What Campus 
User: Jhsjd (Not understood by lex bot to capture campus)
QnA: What Campus. Ask another question or say return to main menu

it should be:
QnA: What Campus

I've tested the conditional chaining demo and behaves the same.

**Comment by rstrahan** [comment]
Hi.. Are you using the example contact flow from QnABot's Connect Wizard? 
If so, you should be able to control the automatic prompting by setting the session attribute `connect_nextPrompt` - you can use Handlebars - example to remove the next prompt completely by setting it to empty string: `{{setSessionAttr 'connect_nextPrompt' ''}}`..  See other examples in the [ConnectWizard sample questions](https://github.com/aws-samples/aws-ai-qna-bot/blob/master/templates/examples/examples/examples/ConnectWizardQnA.json). 
More info on this behavior in this [README](https://github.com/aws-samples/aws-ai-qna-bot/tree/master/workshops/Connect#prompting-the-user)

**Comment by jsenrag** [comment]
I'm setting the connect_nextPrompt variable to '' in the first question "Parking Locations", and thanks to that it won't ask the default prompt the first time, but when the bot does not understand the campus name it will ask for it but concatenating the default prompt. My case is not like in the example where the city is another question altogether but an elicit response using a custom-made bot with a slot type that contains the valid campus names. I've tried to modified the campus bot to call a lambda so I could clear the connect_nextPrompt session variable, without success. The Yes_No bot delivered by QnA its working in the same way.
    On Thursday, May 6, 2021, 02:42:28 PM EDT, Robert ***@***.***> wrote:  
 
 


Hi.. Are you using the example contact flow from QnABot's Connect Wizard?
If so, you should be able to control the automatic prompting by setting the session attribute connect_nextPrompt - you can use Handlebars - example to remove the next prompt completely by setting it to empty string: {{setSessionAttr 'connect_nextPrompt' ''}}.. See other examples in the ConnectWizard sample questions.
More info on this behavior in this README
