### ISSUE TITLE
Invoke Error

### ISSUE THREAD

**Issue by ojo-john** [aws-solutions/qnabot-on-aws#280]
Ever since the new update, tried to create an elicit response but getting an invoke error of "AWS.LexRuntimeV2 is not a constructor".

**Comment by rstrahan** [comment]
Hi @ojo-john - yes, there was an issue with the build process that caused an older AWS SDK version to be used in the fulfillment lambda in the 4.7.1 build. We just published a new build - 4.7.2 - that resolves the issues. Can you upgrade and let us know? Thanks, and apologies for the inconvenience.
