### ISSUE TITLE
XML issue

### ISSUE THREAD

**Issue by saraswathykrk** [aws-solutions/qnabot-on-aws#298]
Hi,

When I try to access the website url i am getting access denied issue. Can you please let me know where I went wrong?

![error](https://user-images.githubusercontent.com/44539281/134208434-64341ae5-974b-4d23-8be0-5687fb8c38fb.png)

Regards

**Comment by bobpskier** [comment]
Can you fill us in on the details? What page are you trying to access when the error is generated? Access Denied in this context might indicate the designer UI page is no longer or that permis are set to deny access to the designer UI.
