### ISSUE TITLE
document the API

### ISSUE THREAD

**Issue by matthewberryman** [aws-solutions/qnabot-on-aws#34]
What I'd like to do is to use the API from other software (in this case https://github.com/MSFREACH/msf-reach ) for updating the list of questions and answers in JSON format, to match new events and reporting links in that software. I've been able to reverse engineer an understanding from the code and Chrome developer tools running on the chatbot designer, but API docs would be nice.

**Comment by JohnCalhoun** [comment]
Matthewberryman,
I aggree, we are working on the v2 of QnA which will alter the api a little (will make it more REST compliant) and we will provide better documentation as part of that change. 

The Api is a AWS ApiGateway so you can go into the AWS Console, got to ApiGateway, find your api, and you can see all the available resources and methods. 

If this an urgent need than i would be happy to write up how the api works before v2.

**Comment by matthewberryman** [comment]
@JohnCalhoun I'd found the API GW and that helped me figure out what APIs map to what bit of code. 👍   
I think I have enough of an understanding for now, so I'm happy to wait until v2 since you have changes planned and it's less work for you to just document the new one. Thanks.

**Comment by JohnCalhoun** [comment]
so plan here is
1) add documentation resources in api template "AWS::ApiGateway::DocumentationPart"
2) use the apigateway to export the swagger file describing API

this swagger file will be the documenation. there are a number of swagger file viewers you could then use. 

(swagger file will update as we add new routes)

**Comment by emerham** [comment]
I know this is an old issue, but did you ever upload the swagger file?
