### ISSUE TITLE
Resource LambdaAccessRole in CF not being used.

### ISSUE THREAD

**Issue by antonykattarath** [aws-solutions/qnabot-on-aws#368]
Resource LambdaAccessRole in CF not being used/referred anywhere else in cf script. Can it be removed?
Also this role is having lambda full access and it's trusted identity is API gateway, Why do API gateway  requires full access to lambda?

**Comment by mohsenari** [comment]
Hey @antonykattarath thanks for notifying us about this. I looked through the source code. Seems like you are right. We'll have to do some testing with `LambdaAccessRole` removed to make sure removing it won't introduce breaking changes.
If testing goes well, we'll have this role removed in future updates.

**Comment by ihmaws** [comment]
Will be included in the next release.

**Comment by michaelin-96** [comment]
@antonykattarath I will be closing this. This should be addressed in the latest release (5.4.1)
