### ISSUE TITLE
CDK Support

### ISSUE THREAD

**Issue by Spartan27** [aws-solutions/qnabot-on-aws#378]
**Is your feature request related to a problem? Please describe.**
There is a requirement of chatbot in one of the tools that our customers use. My team is looking into leveraging the existing QnABot Stack and wondering for a support of beta-gamma-prod like stack setup where changes made in gamma can easily be deployed into prod after proper testing in gamma. SInce we could only find that CFN stack is supported, it would mean to deploy the stack in all three AWS account (beta, gamma, prod) separately and doing any changes in gamma would need to be replicated manually in prod. 

**Describe the feature you'd like**
Wanted to check if there is an equivalent CDK support for the same.

**Comment by mohsenari** [comment]
Hi @Spartan27 thanks for bringing this up. As you mentioned, at the moment we only have the solution as a CloudFormation Stack. There is a plan to rebuild the architecture in CDK, but it is not implemented yet. 
In the mean time for you case of having beta, gamma, and prod environments, you can consider using [CloudFormation's drift detection feature](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/detect-drift-stack.html) to make sure the same changes you have made in beta environment are replicated in your gamma and prod environments.
