### ISSUE TITLE
Lex Rebuild Failure

### ISSUE THREAD

**Issue by manu-idexcel** [aws-solutions/qnabot-on-aws#386]
We are unable to use the rebuild lex functionality from the Admin page. Upon analyzing we found that the questions and answers have a max length limitation, this is restricted from the UI side but when we uploaded from a document this is not validated so the rebuild fails. Although we identified the questions, updated the document, and reuploaded it, we removed a few existing questions, but there were still a few we could not locate and delete.

**Comment by bobpskier** [comment]
Another way to inspect the content is using Kibana to query the elasticsearch cluster directly. You could use the kibana UI to the elasticsearch cluster and find the offending questions and answers. Within the AWS console, find and open the OpenSearch/ElasticSearch console. You'll see one or more domains depending on how many are deployed in the account. Find the one for qnabot based on your stack name and open this domain/cluster. Under general information find Kibana URL and open this link. Login using the same credentials as you would for the Admin UI. Use the "Discover" menu item. Change the Index Pattern to use the index of questions. This will present the raw content. Under available fields select "qid", "questions"', "a". You'll get a table of all qid, questions, and a fields. From here you might be able to locate the offending content.
