### ISSUE TITLE
Expose the Cognito group used for authorization as a CFn parameter.  Allow multiple groups.

### ISSUE THREAD

**Issue by t-jones** [aws-solutions/qnabot-on-aws#396]
**Is your feature request related to a problem? Please describe.**

Many customers have existing identity management / SSO solutions deployed inside their enterprises e.g. Azure AD.  They commonly want to integrate access to the QnABot designer, etc, with this infrastructure, generally using SAML federation.  After a SAML IdP is configured inside cognito, when a user tries to login in, they are denied access.  At this point, the user must be added to the `Admin` group inside cognito.  This can be done manually or with a Lambda function tied to the cognito Post-confirmation hook and maintained by the customer. 

**Describe the feature you'd like**
Add the group used for Cognito authorization as a CFn parameter.  As a bonus, support multiple groups.  Then when a federated identity is added to cognito, the group associated with these users could be added to QnABot and users granted access.

For example, if a federated sign-in identity provider named `AzureAdIdp` is added to the user pool, a group called `region_XXXXXXXXX_AzureAdIdp` is automatically created and all users federating in via this provider are added to the group.  It would be nice to click Update on the stack, add this name to a CFn parameter, and have access to the QnABot designer be granted.

**Comment by tabdunabi** [comment]
The enhancement did not receive enough support to be added to the roadmap

**Comment by sneff91** [comment]
Late to the party, but I am just experiencing dealing with this issue now and it would indeed be a nice feature.
