### ISSUE TITLE
Content Designer "Test All" feature fails to run tests when setting ENFORCE_VERIFIED_IDENTITY is true

### ISSUE THREAD

**Issue by rstrahan** [aws-solutions/qnabot-on-aws#445]
**Describe the bug**
Content Designer "Test All" feature fails to run tests when setting ENFORCE_VERIFIED_IDENTITY is true.  
QnaBot requires a valid JWT token in the Lex request.

**To Reproduce**
Set ENFORCE_VERIFIED_IDENTITY to `true` and run Test All.
View results.. Each test case reports that the user identity could not be verified.

**Expected behavior**
Tests should run using the identity of logged in user.

**Please complete the following information about the solution:**
- v5.1.2

**Comment by ihmaws** [comment]
Thanks for the fix! Released as of v5.2.0
