### ISSUE TITLE
Full screen web UI launched from Content Designer reports errors when ENFORCE_VERIFIED_IDENTITY is true

### ISSUE THREAD

**Issue by rstrahan** [aws-solutions/qnabot-on-aws#447]
**Describe the bug**
Full screen Client Web UI launched from Content Designer reports errors when ENFORCE_VERIFIED_IDENTITY is true. The first request after a page refresh works, but subsequent requests do not. See screenshot.

![image](https://user-images.githubusercontent.com/10953374/163893453-f9ac4a60-12e9-40b8-b89c-514433109e02.png)

**To Reproduce**
Set ENFORCE_VERIFIED_IDENTITY to true and use the Web client to interact with the bot.

**Expected behavior**
Web client should send JWT token in idtokenjwt session attribute for all interactions. 

NOTE: Installing a separate Lex Web UI stack with enable login enabled has not sure problem. This issue relates only to the QnABot wen client (not separate Lex Web UI)

**Please complete the following information about the solution:**
- v5.1.2

**Comment by ihmaws** [comment]
Thanks for the issue!

Looks like this has been fixed as of v5.2.0. Please feel free to reopen if you see it in the latest versions.
