### ISSUE TITLE
Stack fails to deploy when imported in a CDK application

### ISSUE THREAD

**Issue by awskaran** [aws-solutions/qnabot-on-aws#473]
**Describe the bug**

**To Reproduce**
Create a CDK App and a stack. Add the QnA bot as a stack that imports existing Cfn templates

```python
import os

from aws_cdk import Stack
from aws_cdk import aws_sqs as sqs
from aws_cdk import cloudformation_include as cfn_inc
from constructs import Construct

dirname = os.path.dirname(__file__)


class QnABotStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        cfn_inc.CfnInclude(
            self,
            "rQnATemplate",
            template_file=os.path.join(dirname, "cfn/aws-qnabot-main.template"),
            parameters={
                "DefaultKendraIndexId":"3d5710d0-2882-4ddb-bcea-15ad33acad6d",
                "ElasticSearchNodeCount": "2",
                "Email":"awskaran@amazon.co.uk",
                "Encryption":"ENCRYPTED",
                "FulfillmentConcurrency":"0",
                "KibanaDashboardRetentionMinutes": "43200",
                "LexBotVersion": "LexV2 Only",
                "LexV2BotLocaleIds": "en_GB",
                "PublicOrPrivate": "PRIVATE",
                "Username": "Admin",
                "XraySetting": "TRUE"
            },
            load_nested_stacks=dict(
                ExamplesStack=cfn_inc.CfnIncludeProps(
                    template_file=os.path.join(dirname, "cfn/examples.json")
                ),
                ExportStack=cfn_inc.CfnIncludeProps(
                    template_file=os.path.join(dirname, "cfn/export.json")
                ),
                ImportStack=cfn_inc.CfnIncludeProps(
                    template_file=os.path.join(dirname, "cfn/import.json")
                ),
                TestAllStack=cfn_inc.CfnIncludeProps(
                    template_file=os.path.join(dirname, "cfn/testall.json")
                ),
            ),
        )

```

**Expected behavior**
Expected all the stacks in the solution to deploy correctly.

**Please complete the following information about the solution:**
- [ ] Version: v5.1.2
- [ ] Region: eu-west-2
- [ ] Was the solution modified from the version published on this repository? - No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? 
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? No

**Screenshots**
_Issue 1_
<img width="904" alt="Screenshot 2022-06-21 at 14 59 10" src="https://user-images.githubusercontent.com/94186001/174818130-04a05379-8af7-4786-9460-1bc7f2a2ece6.png">

_Issue 2_
<img width="899" alt="Screenshot 2022-06-21 at 12 24 55" src="https://user-images.githubusercontent.com/94186001/174816884-d3d031ca-f9fe-44de-b3db-9f90f02af660.png">

**Additional context**

_Issue 1_
The issue is caused by cyclic dependency in resources.

The solution is to remove "ESInfo" and updating "ESVar" to return "EMPTY" for "ESArn" & "ESAddress" when "CreateDomain" is `false`. "CreateDomain" will never be `false` as its hard-coded to be `true` and currently user is not able to supply information of existing OpenSearch domain.

_Issue 2_

Resources "Alexa" and "QNAInvokePermission" depends on resource "FulfillmentLambdaAliaslive" which is not defined.
Both "Alexa" and "QNAInvokePermission" use the "FulfillmentLambda" arn to build the function alias although it looks like the function alias is not yet propagated/created.

the solution is to create the alias separately from the lambda function resource.

Below template works
[aws-qnabot-main.txt](https://github.com/aws-solutions/aws-qnabot/files/8949648/aws-qnabot-main.txt)

**Comment by cristianbuta** [comment]
The issue still persists. @awskaran did you encounter any other problem except from these ones? 

Trying to figure out if it's worth investing time into cdk with this. thx.

**Comment by cristianbuta** [comment]
Managed to make this work with the solution provided by @awskaran with a few mentions. The template provided above has a syntax error. Parse it as json and you'll easily find it using any modern code editor.

You'll also have to delete AutoPublishAlias & AutoPublishCodeSha256 from Resources/FulfillmentLambda/Properties

**Comment by fbanespo1** [comment]
I am interested in this solution - Is there any entrypoint script? Is this inside a cdk app directory?
Thanks
Tony
