### ISSUE TITLE
QnABot Questions Corrupted

### ISSUE THREAD

**Issue by GGONCONCENTRIX** [aws-solutions/qnabot-on-aws#482]
The bot randomly corrupted a question and customer don’t know how to fix it (looks like the same issue as #2).  They tried deleted the session attribute but it doesn't seem to take.  To fix, needed to manually delete the entire QID and re-enter.

**Comment by ihmaws** [comment]
Hi @GGONCONCENTRIX, unable to reproduce given the provided information.

Closing for now, but if you run into the issue again on the latest version, please create a new issue using the bug report template and we'll have another look.
