### ISSUE TITLE
 FulfillmentLambda function widget is missing in the CloudWatch Dashbaord

### ISSUE THREAD

**Issue by ostapenk** [aws-solutions/qnabot-on-aws#495]
**Describe the bug**
Followed the following official guide https://docs.aws.amazon.com/solutions/latest/qnabot-on-aws/tuning-testing-and-troubleshooting.html to pull the metrics for FulfillmentLambda function and noticed that the widget is missing in the main Cloud Watch Dashboard. 

**To Reproduce**
Review the Cloud Watch Dashboard for QnA bot deployed via CloudFormation stack.

**Expected behavior**
FulfillmentLambda function should be visible in the CloudWatch dashboard.

**Please complete the following information about the solution:**
- [ ] Version: 5.1.2

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [ ] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? no

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by ihmaws** [comment]
Thanks for the report @ostapenk!

The widget has been re-added to the dashboard as v5.2.5
