### ISSUE TITLE
Upgrading from Elastic Search to Open Search

### ISSUE THREAD

**Issue by flick1533** [aws-solutions/qnabot-on-aws#505]
If you want to use Open Search instead of Elastic Search for the Kibana Dashboard you will run into issues. Specifically when clicking the Kibana Dashboard link from the Content Designer URL causing a redirect mismatch error. This is because the Kibana Dash link is to /plugin/kibana/#dashboard?_g=() when it should be /_dashboards/app/home to work with Open Search.

I also found that many resources in the template rely on Elastic Search and the /plugin/kibana endpoint. Would changing the endpoints for these resources cause issues with the stack and bots intended functionality? Is there any plan to make this stack stable and working for OpenSearch 2.3.0?

https://docs.aws.amazon.com/opensearch-service/latest/developerguide/dashboards.html
https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-2.3.0.md

**Comment by ihmaws** [comment]
Thanks for the issue!

The solution has been migrated to OpenSearch v1.3 as of [QnABot v5.3.0](https://github.com/aws-solutions/qnabot-on-aws/blob/main/CHANGELOG.md#530---2023-02-23). All of the mentioned links have been updated accordingly.

We will look to update onto later versions of opensearch (e.g. v2.3, v2.5, etc.) in future releases as all of the necessary prerequisites are met (e.g. Kinesis Firehose support) and the solution is thoroughly tested.
