### ISSUE TITLE
API deployment "stage" of nested "ExportStack" is hard coded

### ISSUE THREAD

**Issue by YutakaShimokawa** [aws-solutions/qnabot-on-aws#514]
**Is your feature request related to a problem? Please describe.**
The Stage parameter is passed when deploying the ExportStack nested from the main CFn stack, but the ExportStack side is hard-coded, so the Stage cannot be changed.

Line 189 of `qnabot-on-aws/templates/export/resources.js` is the following

    stage: "prod",

**Describe the feature you'd like**
Could you please fix the hard coding and allow us to change stages from the main stack?

**Additional context**

**Comment by marcburnie** [comment]
Thanks @YutakaShimokawa for submitting the issue and apologies for the late reply. I'm not 100% certain on what the ask is - do you want the option to set the API Gateway stage name by passing in a parameter to the parent Cloudformation template?

**Comment by kroeter** [comment]
Closing this due to lack of response. Please open a new issue if you would like our team to address.

**Comment by marcburnie** [comment]
The prod stage value has been replaced with a parameter from the parent stack in the v5.4.2 release (see: https://github.com/aws-solutions/qnabot-on-aws/blob/feature/v5.4.2/templates/export/resources.js#L207).
