### ISSUE TITLE
Using cloudformation template to deploy on other cloud

### ISSUE THREAD

**Issue by piotr-dziubek** [aws-solutions/qnabot-on-aws#515]
**Describe the bug**
We want to deploy our qnabot template to another cloud. So I've made it public accessible in s3, and if I want to run it on another cloud via cloud formation template (public.json) - I've ended with errors like this in the screenshot
![image](https://user-images.githubusercontent.com/97026979/198225863-92b9b029-3d44-44ba-bea1-1f0ebdeb2466.png)
I've tried to do this on the root account with full access but with no success. On the root cloud - if I run npm commands - it works. 

My question is - is this possible to do like that ? to have our own template in my cloud and send the link to the template to another cloud so that other users can install it?

Thank You

**Comment by bobpskier** [comment]
I believe your question is if you can host the templates built by this project in an S3 bucket in your AWS account and have them deployed via CloudFormation in a different AWS account. 

The bin/update-public.sh does just this. It uploads the results of a build to a target bucket defined in the root level config.json file. See publicBucket and publicPrefix in this file.

  "publicBucket": "",
  "publicPrefix": "artifacts/aws-ai-qna-bot",

The region specified in config.json should also be set properly for where this bucket exists. 

The target publicPublic bucket needs to have Bucket Versioning enabled and needs to be set such that Objects can be public. Once you have the bucket set and config.json set, complete a build running "npm run upload", cd into the bin folder, finally execute "./update-public.sh --run".

This will upload the templates and the resulting build artifacts to your S3 bucket. The public.json template can then be referenced by a separate AWS account.

**Comment by piotr-dziubek** [comment]
Thank you @bobpskier  - now it works!
