### ISSUE TITLE
Full policies/permissions list for deploying the solution

### ISSUE THREAD

**Issue by iamcrisb** [aws-solutions/qnabot-on-aws#546]
**Is your feature request related to a problem? Please describe.**
It would be very helpful to provide a full list of permissions that the cloudformation template requires for full deployment, especially for use-cases when this has to be deployed in a CI environment where least privilege is mandatory

**Describe the feature you'd like**
A full list of permissions that a role requires for deploying the solution.

**Additional context**
-

**Comment by ihmaws** [comment]
Hey @cristianbuta, thanks for this request.

Unfortunately, with the large number of services touched by the solution, it's not an easy thing to capture at this time. But I do like the general idea of providing this along side the solution. I agree that it could be useful for customers to have access to.

I'm unable to commit to a timeline as this isn't a key priority of ours; however, it is something we will try to investigate over the coming months. I'll keep this issue open and let you know if we make any progress.

**Comment by kroeter** [comment]
Resolving this solution as we have not prioritized it for our roadmap. Please reach out with other enhancement ideas if you have them.

**Comment by iamcrisb** [comment]
nice, thank you @kroeter !
