### ISSUE TITLE
Wondering if there is a .xml or draw.io for the diagram so I can pull into Design Inspector for a task I am working on?

### ISSUE THREAD

**Issue by darknessOverwhelming** [aws-solutions/qnabot-on-aws#562]
Wondering if there is a .xml or draw.io for the diagram so I can pull into Design Inspector for a task I am working on? Thank you

**Comment by ihmaws** [comment]
@darknessOverwhelming thanks for the idea. You can pick up the xml for your task here: https://github.com/aws-solutions/qnabot-on-aws/pull/563

We'll merge it in for the next release.
