### ISSUE TITLE
qnabot showing qid::topic.key when user clicks on any topics

### ISSUE THREAD

**Issue by sidboh85** [aws-solutions/qnabot-on-aws#573]
qnabot is returning qid::topic.key when user clicks on any pre-defined topics. This gets resolved if I update the config to have the topic value in place of the topic key but when it comes to previous topics, I face the same issue again. For example if user clicks on Previous Topics, topics are coming up and when user selects any of the topic, the qid::topic.key again comes up.

**Comment by ihmaws** [comment]
Hi @sidboh85, can you please update this issue using the `Bug Report` template. We'd need to know more information such as which version of the solution you are on, steps to reproduce, and any logs/screenshots you have to describe the issue.

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/111378641/228004193-f34f9eac-ef82-4496-9948-f88f76ee0357.png">

**Comment by sidboh85** [comment]
sure, will do. Thanks!
