### ISSUE TITLE
No results with short queries (although they do score in Tester in ES)

### ISSUE THREAD

**Issue by bigrig2212** [aws-solutions/qnabot-on-aws#58]
## Expected Behavior
Type "modify" in the Client chat UI. Should fulfill answer "Admin.001"

Using the default content in the  admin **_tester_**, a search for "modify" returns answer "Admin.001" with a score of 1.97. 

## Actual Behavior
When you type "modify" into the Client chat UI, it says "Sorry, can you please repeat that?"

## Steps to Reproduce the Problem

  1. Just search for "modify"

Note: the problem goes away if you were to add "modify" as an alternate question for Admin.001. 

I don't see the unsuccessful Client-side queries in the logs... am thinking they cut out somewhere in Lambda before getting logged? Or there is an ES score threshold? Would love a point in the right direction to debug. Thx.

**Comment by bigrig2212** [comment]
I think i've traced down the issue (but don't have solution). Lex is not recognizing these shorter questions as utterances that match the intent, so they're not being forwarded on to Lambda/ES (which is why they don't show up in the logs). 

Is there a way to tell Lex to recognize everything? 

It's more limiting that my example above conveys, which is quite terse. It fails more broadly. For example, the question "check status of reservation" fails also.

**Comment by bigrig2212** [comment]
Hi. Yea, that solves the problem in an immediate sense. But limits, I think, the utility of ES under the hood. I'd think that if there's a high scoring response in ES, we'd want to show it. It makes the proposed ingestion utility much more functional: https://github.com/awslabs/aws-ai-qna-bot/issues/54.

**Comment by JohnCalhoun** [comment]
you are correct, the problem is that if Lex does not recognize the utterance then the lambda does not even get called and a static response is returned. In many lex use cases this makes sense but not for our use case. 

also, since this a behavior of lex there are limited things that QnABot can do. :(

**Comment by tiborATandoverlab** [comment]
First of all, brilliant work guys!
Just out of curiosity, would it not give better results (through NLU) if those examples were intent utterances, as in a normal use case? Why are these examples slot type examples, any benefits over the utterances?
And a cheeky question, if the ES search is the only intent (fulfilment), why bother using Lex at all?
