### ISSUE TITLE
Separate OpenSearch instance selection from the "Encryption" parameter

### ISSUE THREAD

**Issue by dthvt** [aws-solutions/qnabot-on-aws#599]
**Is your feature request related to a problem? Please describe.**

Separate OpenSearch instance selection from the "Encryption" parameter.

**Describe the feature you'd like**

A new parameter "OpenSearchInstanceType" or the like that allows selection of OpenSearch instance types independent of Encryption.

The "Encryption" parameter should still control whether the OpenSearch domain is encrypted.

**Additional context**

Modern OpenSearch instance types all support encryption at rest, and there's no reason I shouldn't be able to encrypt data a rest to comply with corporate policies while running a smaller-than-production sized domain.

**Comment by jangidms** [comment]
Hi @dthvt 
Thank you for reporting this. We are looking into this and will update after analysis

**Comment by jangidms** [comment]
Hi @dthvt 
Thank you for your contribution. We are planning to include this in upcoming release.
We'll keep you updated on progress

**Comment by jangidms** [comment]
Hi @dthvt
This change has been incorporated in release v5.5.0
Thanks for your contribution
