### ISSUE TITLE
Custom domain cannot be configured for ap-northeast-1 region

### ISSUE THREAD

**Issue by YutakaShimokawa** [aws-solutions/qnabot-on-aws#605]
**Describe the bug**
After deploying a stack to the ap-northeast-1 region and configuring a custom domain, sigv4 authentication fails and login becomes impossible.
<img width="686" alt="image" src="https://user-images.githubusercontent.com/114559805/235102111-2cf3696b-ee65-4fb4-b3f4-fd572995073c.png">

**To Reproduce**

1. Deploy in  ap-northeast-1 region 
2. Configure custom domain refering to the following manual

https://github.com/aws-solutions/qnabot-on-aws/blob/771b4b465266c19fb863a38c2aa0cd80bf665e96/docs/custom_domain_name_setup/README.md

**Expected behavior**
Able to login

**Please complete the following information about the solution:**
- [x] Version: v5.2.2

- [x] Region: ap-northeast-1
- [x] Was the solution modified from the version published on this repository?: No
- [x] If the answer to the previous question was yes, are the changes available on GitHub?: -
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?: Yes, and no alart
- [x] Were there any errors in the CloudWatch Logs?: No

**Comment by YutakaShimokawa** [comment]
I think it is probably due to the fact that the [aws4](https://www.npmjs.com/package/aws4) library in the following section is set to us-east-1 when the region cannot be determined from the URL path.
https://github.com/aws-solutions/qnabot-on-aws/blob/ecdf9f887bb1cd0688421b57c6809eea6ccd4609/website/js/lib/store/api/actions/index.js

**Comment by ihmaws** [comment]
Thanks for the report @YutakaShimokawa and sorry for the delay in getting back to you!

The team will have a look and add it into the backlog for investigation.

**Comment by jangidms** [comment]
Hi @YutakaShimokawa 
Sorry for the delayed response. We are planning a fix for this issue. Please continue to monitor repo for updates

**Comment by jangidms** [comment]
Hi @YutakaShimokawa
This issue has been fixed in release 5.4.2
