### ISSUE TITLE
Additon of Lex buttons breaks Voice channel response

### ISSUE THREAD

**Issue by lgaffney13** [aws-solutions/qnabot-on-aws#607]
**Describe the bug**
When using QnABot in an Amazon Connect Contact Flow, if Lex buttons are added to the question, QnABot no longer returns voice responses.

**To Reproduce**
On QnABot v5.3.2 integrate QnABot to an Amazon Connect Contact Flow
For a given question, add Lex buttons
Call into the number assigned to the Contact Flow
Ask the question where you have added the Lex buttons
No response is returned

**Expected behavior**
QnABot should return the answer to the question

**Please complete the following information about the solution:**
- [ ] Version: [e.g. v0.0.1]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [ ] Region: us-west-2
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by ihmaws** [comment]
Thanks for the report @lgaffney13, a fix has been released as of [v5.3.4](https://github.com/aws-solutions/qnabot-on-aws/releases/tag/v5.3.4).
