### ISSUE TITLE
cloudformation stack roleback issue

### ISSUE THREAD

**Issue by muntherqasaimeh** [aws-solutions/qnabot-on-aws#614]
Hello.
I'm facing issue everytime I create a cloudformation stack for QNAbot I got error "[ResponseBotQNADateNoConfirmV2, ResponseBotQNADateV2, ResponseBotQNADayOfWeekV2 " 
You can find screenshot for this issue 
Can you please tell me why this happened and how to solve this ?
thanks.
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/80498650/7784af6c-4cc2-4812-8008-1bc533d38378)

**Comment by ihmaws** [comment]
Hi @muntherqasaimeh, thanks for the report. Can you please include additional information found in the bug report template (e.g. Solution Version).

You can find additional information about this particular error by going into the `ExamplesStack` and viewing the error there. You may need to filter by `Deleted` in the Cloudformation console to find this nested stack. That should tell you why those resources failed to create.

Once you share the information above we should be able to figure out what's going on. A random shot in the dark right now, maybe your stack name is too long? Try shortening it to see if that helps.

**Comment by muntherqasaimeh** [comment]
Hi
I opened the deleted stack and I found this issue here 
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/80498650/87993c1a-8e9e-4e82-80b1-ea7e750b9314)

**Comment by ihmaws** [comment]
Closing ticket for now. If you are still experiencing issue, please create a new issue using the bug report template to include the additional information required to reproduce the bug.
