### ISSUE TITLE
Ability to set Language using native spellings. 

### ISSUE THREAD

**Issue by feelec1** [aws-solutions/qnabot-on-aws#615]
**Is your feature request related to a problem? Please describe.**

If a potential user of the QnA bot wants to select their own language using the handlebar syntax this can only be done if the spelling of the language is typed in English (for example French, Spanish...) 

If the user tries to type their native spelling of that language (for example Français, Español) then this fails with the empty response being returned. 

**Describe the feature you'd like**

A user can type in a supported language using the English and native spelling of that language.

**Additional context**

Also to allow a user to type in a phrase to also set the language (for example, 'me gustaria hablar en español')

**Comment by feelec1** [comment]
For additional context the code looks like its looking up the language in the supportedLanguages.js file and if there isn't a match its failing to set the language. 

You can include the native spellings of those languages (I've tested this) and it does work but there are some exceptions. It has issues matching the 'ç' in Français. 

Also, it doesn't detect a variation when setting the language such as 'me gustaria hablar en español' or I want to speak in Spanish

**Comment by kroeter** [comment]
Hey Feelec1 - we're working on a feature to enable multi-language support within QnABot that may be able to address your request. More to follow.

**Comment by bios6** [comment]
Hi @feelec1 , we just launched v5.5.0 today for QnABot. This supports a new Parameter in the CloudFormation Stack that will support Opensearch Language analyzer for the index. With this new feature, it will allow a more accurate Native Language use.

**Comment by bios6** [comment]
Closing this issue now.
