### ISSUE TITLE
Lambda Recursion Detection causing failed deployments on new accounts

### ISSUE THREAD

**Issue by ihmaws** [aws-solutions/qnabot-on-aws#618]
**Describe the bug**
On June 26, 2023 (dates may vary per region), AWS Lambda launched [recursive loop detection](https://docs.aws.amazon.com/lambda/latest/dg/invocation-recursion.html) which stops the invocation of a Lambda function after 16 recursive calls. Customers who trigger this new rule will fail to deploy the template and get an email notification of the error.

Alternatively, if AWS Lambda identified that within the 3 months prior to this feature being enabled, a recursive loop was detected in your account, this feature was not enabled in your account and recursive loops will not be terminated. Customers were sent a notification email if this was the case (see sample screenshot below). You must contact support if you wish to have this feature enabled on your account (see instructions provided in the email).

**To Reproduce**
Deploy a solution version <=5.3.4 in an account with recursive loop detection enabled. Although it may not always happen, the `OpenSearchDomainUpdate` should fail to deploy because recursive calls to itself should trigger the new rule.

**Expected behavior**
Deployment should complete successfully.

**Please complete the following information about the solution:**
- [v5.3.4] Version: [e.g. v0.0.1]
- [us-east-1] Region: [e.g. us-east-1]
- [N] Was the solution modified from the version published on this repository?
- [N/A] If the answer to the previous question was yes, are the changes available on GitHub?
- [N/A] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [N/A] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

### CloudFormation error
<img width="1349" alt="image" src="https://github.com/aws-solutions/qnabot-on-aws/assets/111378641/18ac0eb8-9aa2-4317-9866-9d96ed1f5aeb">

### Recursive Loop detection email
<img width="1268" alt="image" src="https://github.com/aws-solutions/qnabot-on-aws/assets/111378641/0f5aca49-5017-4566-89ef-507258b8b25b">

### Recursive Loop disabled in your account email
<img width="1269" alt="image" src="https://github.com/aws-solutions/qnabot-on-aws/assets/111378641/8ebf681b-4601-4365-b8f3-6d53ed03cf5b">

**Additional context**
❗This change does not affect the operation of an existing deployment in anyway❗ The `CFNLambda` function in question is only used at deployment time (Stack Create/Update) and will not affect the operation of the solution for existing (or new) stacks that have deployed successfully.

**Update:** The Lambda function in question has been updated to prevent this recursion from occurring going forward. A fix has been released in [v5.3.5](https://github.com/aws-solutions/qnabot-on-aws/releases/tag/v5.3.5)

**Comment by ihmaws** [comment]
Fix released as of [v5.3.5](https://github.com/aws-solutions/qnabot-on-aws/releases/tag/v5.3.5). Will keep issue open for a few weeks for any discussions.

**Comment by fhoueto-amz** [comment]
Closing this now
