### ISSUE TITLE
Make OpenSearch Clean Metrics METRICS_DELETE_RANGE_MINUTES and FEEDBACK_DELETE_RANGE_MINUTES configurable in Cloudformation script

### ISSUE THREAD

**Issue by justinramnandan** [aws-solutions/qnabot-on-aws#643]
**Describe the bug**
We were not aware that the OpenSearch metrics data range was cleaned up for data older than 30 days

**To Reproduce**
Once the solution is implemented longer than 30 days qnabot metrics table will delete older data.

**Expected behavior**
Expected behavior would be to allow these environment variables be configurable so we can preserve historical data when the solution is deployed.

**Please complete the following information about the solution:**
- [ ] Version: QnABot with admin and client websites - Version v5.4.1

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [ ] Region: us-west-2
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? N/A
- [ ] Were there any errors in the CloudWatch Logs? No

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by rstrahan** [comment]
Hi @justinramnandan, You can set the retention period to use by setting the CloudFormation Stack parameter `KibanaDashboardRetentionMinutes` when you deploy or update the QnABot stack - is this what you need?
 
See: https://docs.aws.amazon.com/solutions/latest/qnabot-on-aws/step-1-launch-the-stack.html
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/10953374/5360f355-a976-4b26-9ad9-1d04e74513d6)

**Comment by justinramnandan** [comment]
This is what I was looking for. Thanks for pointing me in the right direction.
