### ISSUE TITLE
Lex rebuild is failing due to 'QnAIntent' being considered a built-in intent name

### ISSUE THREAD

**Issue by cristi-constantin** [aws-solutions/qnabot-on-aws#658]
**Describe the bug**
If I rebuild Lex from the content designer, it fails with Rebuilding : FAILED: An error occurred (ValidationException) when calling the CreateIntent operation: The specified intent name conflicts with a built-in intent name. Please use a different name.
Initially, it was a failure related to UpdateIntent, but then I deleted the intent to test it out. It also fails on create.

I've also tried creating a new bot and giving the intent name as 'QnaIntent'. That also fails with: 'An error occurred
The specified intent name conflicts with a built-in intent name. Please use a different name.'

It seems that this intent name is now already in use / considered as an Amazon built-in intent name.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Please complete the following information about the solution:**
- [5.4.2] Version: [e.g. v0.0.1]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [us-east-1] Region: [e.g. us-east-1]
- [No] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [No] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [Don't know] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by marcburnie** [comment]
Hi @cristi-constantin - thanks for reporting the issue. I also noticed that our test deployments ap-southeast-2 failed last night due to the same reason. Curiously, similar deployments in other regions did not. Let us look into this and get back to you.

**Comment by hablat** [comment]
I'm also running into this when trying to spin up a new stack.  Is there currently a workaround?

**Comment by marcburnie** [comment]
There is currently no workaround. If you are spinning up a new stack and the region doesn't matter to you, the only impacted regions are us-east-1 and ap-southeast-2, so you should be able to deploy in us-west-2 for example.

**Comment by hablat** [comment]
Unfortunately we can only spin it up on us-east-1. Do you have a sense of when this will work again?

**Comment by marcburnie** [comment]
We're actively working on this but, unfortunately, I cannot commit to a timeline. We're treating this as high priority so we should have an update soon.

**Comment by marcburnie** [comment]
@cristi-constantin @hablat - the issue should be resolved now. Our builds are passing in all regions. Please try again. Let us know if your issue has not been resolved.

**Comment by cristi-constantin** [comment]
@marcburnie - confirmed as resolved.

**Comment by hablat** [comment]
@marcburnie Thank you, its working for on creation for me as well.
