### ISSUE TITLE
Getting Syntax Error on LLM Model Lambda function

### ISSUE THREAD

**Issue by shivangisharma991** [aws-solutions/qnabot-on-aws#662]
**Describe the bug**
After setting up the QnABot as suggested in AWS Blog (https://aws.amazon.com/blogs/machine-learning/deploy-generative-ai-self-service-question-answering-using-the-qnabot-on-aws-solution-powered-by-amazon-lex-with-amazon-kendra-and-amazon-bedrock/), I am getting error when testing the Bot. After investigating I found the error is in the LLM Lambda function.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Please complete the following information about the solution:**
- [ ] Version: [e.g. v0.0.1]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [x] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [x] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
![Screenshot 2023-11-14 at 13 50 52](https://github.com/aws-solutions/qnabot-on-aws/assets/69389188/8f269141-5f05-4e1e-839d-c681baf994ca)
![Screenshot 2023-11-14 at 14 25 14](https://github.com/aws-solutions/qnabot-on-aws/assets/69389188/cac2b961-4174-4712-9fac-85987c4dfb69)

**Additional context**

**Comment by marcburnie** [comment]
This appears to be caused by an incorrect setting in the content designer. Can you please check the setting you have for `LLM_GENERATE_QUERY_MODEL_PARAMS` and verify it is a correct JSON object as specified in the README.

**Comment by fhoueto-amz** [comment]
Hi
Can you also please clarify the version of QnAbot that you are using? Which LLM are you using? The blog pointed to states "When you deploy QnABot, you can choose to automatically deploy an open-source LLM model ([Falcon-40B-instruct](https://huggingface.co/tiiuae/falcon-40b-instruct)) on an [Amazon SageMaker](https://aws.amazon.com/sagemaker/) endpoint." Is it what you are using or you are configuring your own LLM model via the plugin. Please also share which LLM model you are using and steps taken to set it up.

**Comment by shivangisharma991** [comment]
> This appears to be caused by an incorrect setting in the content designer. Can you please check the setting you have for `LLM_GENERATE_QUERY_MODEL_PARAMS` and verify it is a correct JSON object as specified in the README.

one of the value was wrongly mentioned, after correcting I see some response coming now from QnABot, thanks for response. I will proceed further and validate other aspects.

**Comment by marcburnie** [comment]
That's good to hear. Good luck!
