### ISSUE TITLE
ALT_SEARCH_KENDRA_FALLBACK_CONFIDENCE_SCORE not honored when LLM_QA_USE_KENDRA_RETRIEVAL_API=true

### ISSUE THREAD

**Issue by shieldsjared** [aws-solutions/qnabot-on-aws#664]
**Describe the bug**
When leveraging the Kendra fallback index, and use of the Kendra Retrieval API is enabled, it _appears_ that the `ALT_SEARCH_KENDRA_FALLBACK_CONFIDENCE_SCORE` setting is not honored as a threshold. To use the setting, you must set `LLM_QA_USE_KENDRA_RETRIEVAL_API` to `false` (but then you're using the Query API and getting a shorter excerpt from Kendra).

**To Reproduce**
- `LLM_QA_ENABLE` = `true`
- `LLM_QA_USE_KENDRA_RETRIEVAL_API` = `true`
- `ALT_SEARCH_KENDRA_FALLBACK_CONFIDENCE_SCORE` = `VERY_HIGH`
- Perform a search that should result in a fallback to Kendra, and verify that only documents with a `VERY_HIGH` confidence are included

**Expected behavior**
The `ALT_SEARCH_KENDRA_FALLBACK_CONFIDENCE_SCORE` setting should be honored whether the Kendra Query API is used OR the Kendra Retrieve API. I could not find documentation stating that this otherwise would not work. 

**Please complete the following information about the solution:**
- Version: **5.4.3**
- Region: **us-east-1**
- Was the solution modified from the version published on this repository? **No**
- Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? **Yes**
- Were there any errors in the CloudWatch Logs? **None of relevance**

**Comment by marcburnie** [comment]
Thanks for reporting this. Let us take a look and get back to you.

**Comment by marcburnie** [comment]
Hi @shieldsjared - currently QnABot does not filter results using the Kendra Retrieval API. I can update the documentation to clarify where the ALT_SEARCH_KENDRA_FALLBACK_CONFIDENCE_SCORE is used. With that being said, will this solve your problem? Do you still want a mechanism to filter Kendra retrieval results?

**Comment by marcburnie** [comment]
We will update the documentation during the next release. If you want a new setting for filtering Kendra Retrieval results then please submit a feature request, since this functionality does not currently exist.
