### ISSUE TITLE
Provide better error message

### ISSUE THREAD

**Issue by abilash44** [aws-solutions/qnabot-on-aws#665]
**Is your feature request related to a problem? Please describe.**
When questions are entered and saved , they disappear on refresh.  This happens when EMBEDDINGS_ENABLE was set to true in custom deployment.

**Describe the feature you'd like**
There should be better error message to track down what is happening.

**Additional context**
If there is no error message and since this solution has too many moving parts an user would not be able to identify what or where somethign is not working.

**Comment by marcburnie** [comment]
Thanks for creating a new issue for the error reporting. We'll add this to our backlog and update this ticket.

**Comment by fhoueto-amz** [comment]
Fixed in v6.0.0
