### ISSUE TITLE
Make the settings standard through out.

### ISSUE THREAD

**Issue by abilash44** [aws-solutions/qnabot-on-aws#666]
**Is your feature request related to a problem? Please describe.**
Make the text for true or false the same all over. Some places it is true and some TRUE. 

**Describe the feature you'd like**
A better formatting will help avoid any problem with case sensitive settings.

**Additional context**
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/7634986/4de1ab7a-ca3c-44b1-a76c-afef8b23ae45)

**Comment by marcburnie** [comment]
Thanks for submitting this issue. FYI - these values get parsed into boolean values as you would expect. We will make this consistent and update this ticket once resolved.

**Comment by marcburnie** [comment]
This has been resolved as of v5.5.0.
