### ISSUE TITLE
Enhanced logging and error messages.

### ISSUE THREAD

**Issue by abilash44** [aws-solutions/qnabot-on-aws#668]
**Is your feature request related to a problem? Please describe.**
I made a mistake of using the data id instead of the index id for the kendra index. 

**Describe the feature you'd like**
1. After enabling chat debug as true some error message should appear in the client side. Nothing appears I only see empty response
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/7634986/997b0eb9-0071-4f3b-a302-80c527e5c4e8)
2. Some form of validation before hit save to inform the entered value is wrong. 
3. Please provide a doc section for looking at logs. There are so many services here I do not know which cloudwatch logs to look at. It will help me find out what is wrong and try fixing it myself.

**Additional context**
I just went around in circles for a few hours creating and deleting a dozen stacks. lol.

**Comment by marcburnie** [comment]
Hi @abilash44 - unfortunately, the debug does not appear if there is an unhandled exception on the backend. The place you want to look for errors with the chat client is in the fulfillment lambda's log: https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups$3FlogGroupNameFilter$3Dfulfillment.

We're actively working on this already, so we will keep this issue open for updates.

**Comment by abhirpat** [comment]
Hi @abilash44 - could you please try testing this in latest QnaBot version 5.5.0? You can deploy QnaBot using template available in https://aws.amazon.com/solutions/implementations/qnabot-on-aws/
