### ISSUE TITLE
End of support for Node.js 16, update to Node.js 20

### ISSUE THREAD

**Issue by amendlik** [aws-solutions/qnabot-on-aws#673]
**Is your feature request related to a problem? Please describe.**
I received an end-of-support notification for Lambda functions using Node.js 16:

> We are contacting you as we have identified that your AWS Account currently has one or more AWS Lambda functions using the Node.js 16 runtime.
> 
> We are ending support for Node.js 16 in Lambda on June 12, 2024. This follows Node.js 16 End-Of-Life (EOL) reached on September 11, 2023 [1].
> 
> As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in several stages. Starting on June 12, 2024, Lambda will no longer apply security patches and other updates to the Node.js 16 runtime used by Lambda functions, and functions using Node.js 16 will no longer be eligible for technical support. Also, Node.js 16 will no longer be available in the Console, although you can still create and update functions using Node.js 16 via AWS CloudFormation, the AWS CLI, AWS SAM, or other tools. Starting July 15, 2024, you will no longer be able to create new Lambda functions using the Node.js 16 runtime. Starting August 15, 2024, you will no longer be able to update existing functions using the Node.js 16 runtime.
> 
> We recommend that you upgrade your existing Node.js 16 functions to Node.js 20 before June 12, 2024. A list of your Node.js 16 functions can be found in the 'Affected resources' tab of the AWS Health Dashboard.
> 
> End of support does not impact function execution. Your functions will continue to run. However, they will be running on an unsupported runtime which is no longer maintained or patched by the AWS Lambda team.

**Describe the feature you'd like**
Per the recommendation above, update functions to use the Node.js 20 runtime.

**Comment by abhirpat** [comment]
Hi @amendlik , could you please confirm which version of QnaBot? Kindly note that latest QnaBot is already using Node 18 and is available for you to upgrade.

**Comment by amendlik** [comment]
You are right. I see that the Node version was moved to 18 recently.

**Comment by thejang90** [comment]
Hi @amendlik, what is this mean "you will no longer be able to update existing functions using the Node.js 16 runtime."? Are we not able to run lambda using the Node.js 16?. And, Do we convert code which exist fucntion to fit node.js 18 runtime?
