### ISSUE TITLE
Faceboom integration

### ISSUE THREAD

**Issue by dangollayan** [aws-solutions/qnabot-on-aws#686]
Is there a way to integrate this with facebook?

**Comment by fhoueto-amz** [comment]
Hi @dangollayan 
Thanks for your feedback. Can you please elaborate on what you mean by integration with Facebook, for example by providing a use case or workflow?

**Comment by dangollayan** [comment]
Hi @fhoueto-amz, we are planning to use the QnA bot on Facebook via Facebook chat messenger. Is there a guide or a way we can look that up?

**Comment by bobpskier** [comment]
@dangollayan QnABot is at its core just a Lex V2 bot. The general steps for integration to facebook messenger can be found at https://docs.aws.amazon.com/lexv2/latest/dg/deploy-facebook-messenger.html. You would use the primary qnabot lexv2 bot and then Add a channel per the instructions in Step 2. This is the basic process you'd follow to start the integration.

**Comment by dangollayan** [comment]
Thanks bob!

**Comment by fhoueto-amz** [comment]
Thanks Bob. @dangollayan I am closing this.
