### ISSUE TITLE
Unable to use lambda on chaining

### ISSUE THREAD

**Issue by dangollayan** [aws-solutions/qnabot-on-aws#687]
When using a lambda in chaining, it doesn't go with the document chain
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/113376990/38991723-8fbd-4f5b-bde2-647797e1c733)

As I've checked the code evaluateConditionalChaining, there is invokeLambda function where the return is an array that includes req, res, and payload
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/113376990/dbed0dfc-6790-45e6-b7e6-37a4a5af2546)

but upon checking the invokeLambda function it only returns req and res
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/113376990/f2c3e466-e54e-4c5b-a266-cd5fe0dff959)

I think this is the reason why it doesn't get the payload, because it doesn't return the payload in the invoke lambda function.

Kindly validate if my assumption is correct.

**Comment by fhoueto-amz** [comment]
Thanks for reporting this. We will review and revert to you.

**Comment by dangollayan** [comment]
any update on this?

**Comment by jangidms** [comment]
Hi @dangollayan 
Your assumption is correct. Thanks for reporting this.
We'll plan a fix for this issue.

Thanks

**Comment by dangollayan** [comment]
HI @jangidms , while I wait for fix, can you guide me where should I apply the fix on the code in the deployed qna bot?

I tried updating the Es-Proxy layer
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/113376990/afef4192-100f-414f-a8f0-872802eeddfd)
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/113376990/b1ce2c1f-1910-4cc3-8e84-a4f508256a2c)
and set all the function to use the new version
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/113376990/c9df7864-e687-4840-8814-056ee4d8e959)

but still it didn't reflect on our end.

**Comment by jangidms** [comment]
Hi @dangollayan 
You can follow below steps to update Fulfillment lambda to use updated Esproxy layer.
1. Download the Esproxy layer
2. Make changes to Esproxy layer and upload updated layer zip file
3. From Fulfillment lambda, under Code -> Layers -> Edit Esproxy layer version to be latest 
4. From Fulfillment lambda -> Version -> Publish new Version
5.  From Fulfillment lambda -> Aliases -> Edit live alias to point it to new lambda version

Please let me know if you have any further questions

Thanks

**Comment by bios6** [comment]
Hi @dangollayan  this issue should be resolved with the latest release v5.5.1. Thank You!
