### ISSUE TITLE
using Anthopic / claude causes error due prompt malformed

### ISSUE THREAD

**Issue by ensamblador** [aws-solutions/qnabot-on-aws#688]
**Describe the bug**
The default LLM prompt used by Generative AI responses (Content Designer: LLM_GENERATE_QUERY_PROMPT_TEMPLATE and LLM_QA_PROMPT_TEMPLATE) missing the **Human: .... Assistant:** parts which causes an error invoking the Lambda function.

**To Reproduce**
Just using Lambda LLM plugin and Anthopic /Claude models.

**Expected behavior**
the expected behaviour is the intended: invoke the llm and the a response.

**Please complete the following information about the solution:**
- (SO0189) QnABot with admin and client websites - Version v5.4.5

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [x ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [x ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by fhoueto-amz** [comment]
Thanks. We will look into this and revert back

**Comment by abhirpat** [comment]
Hi Enrique,

Please provide below details -

1. What is the error?
2. Does this occur only when you're using plugins or Sagemaker as well? If it's specific to anthropic pluging - it could be related to https://github.com/aws-samples/qnabot-on-aws-plugin-samples 

Thank you,
Abhishek

**Comment by ensamblador** [comment]
Hi Abhishek

1. The error arises when you invoke LLM Lambda used from QNABOT-BEDROCK-EMBEDDINGS-AND-LLM repo ( not sagemaker) **using Anthropic / Claude models**. This is the error showed in the QnABot Client when you enable debug responses:

**Source: unknown, Errors: ["Lambda exception: An error occurred (ValidationException) when calling the InvokeModel operation: prompt must end with an "\n\nAssistant:" turn..."]]** Same can be seen in cloudwatch

I believe the reason that LLM_GENERATE_QUERY_PROMPT_TEMPLATE and LLM_QA_PROMPT_TEMPLATE (in settings in QnABot Designer Settings) missing the  Human: .... Assistant: prefix suffix. I added that and worked, but it´s a restriction that only affects claude models.

**Comment by abhirpat** [comment]
THank you, Enrique. As discussed, this appears to be specific to prompt template with plugin. I would recommend to report the issue to https://github.com/aws-samples/qnabot-on-aws-plugin-samples instead.
