### ISSUE TITLE
Use a response bot that returns empty messages generates an exception

### ISSUE THREAD

**Issue by jeve7** [aws-solutions/qnabot-on-aws#689]
**Describe the bug**
I am working on a migration from 5.4.5 to 5.5 and found a situation with 5.5 when using response bots. In 5.4.5 when a bot is called, the field "message" returned can be empty (i.e. "message": "") and it works. For example the test bots (i.e "QnAAge") returns "OK." as closing response, however the fallback intent is empty. In 5.5 if the message field returned by the bot is empty I see this exception in the fulfillment lambda logs: 
"**___type": "ValidationException", "message": "1 validation error detected: Value at 'text' failed to satisfy constraint: Member must have length greater than or equal to 1_**". 
In the stack trace it shows this: 
"_**at async translate_res (/var/task/lib/middleware/lexRouter.js:62:24)"**_" 

The same exception happens if the response bot (i.e. QnAAge) doesn't provide a message back. To test you can open the bot and delete the message "OK." located in the "Closing Response" of the "AgeIntent".

Appears like a translation request. My bot is configured with multi-language support disabled.

**To Reproduce**
I configured a response bot as described in the documentation [here](https://docs.aws.amazon.com/solutions/latest/qnabot-on-aws/configuring-the-chatbot-to-ask-the-questions-and-use-response-bots.html ):
To generate the error:
- Initiate session
- Type/say: "Ask my name"
- Provide first name and last name
- Confirm (Say yes)
- When ask for the age say anything that move you to "fallbackIntent"(i.e "Why do you need it?")
- An error happens. Check the "FulfillmentLambda" log in CloudWatch to see the error.

Alternative:
- Delete the message "OK." located in the "Closing Response" of the "AgeIntent".
- Execute the test again but this time provide a number when asking for the age.
- An error happens. Check the "FulfillmentLambda" log in CloudWatch to see the error. 

**Expected behavior**
No exception should happen and the bot should continue and present the message configured in "ELICIT_RESPONSE_BOT_FAILURE_MESSAGE".
In case of a bot not answering with message it should continue the regular flow.

**Please complete the following information about the solution:**
- [ ] Version Not Working: 5.5
- [ ] Version Working: 5.4.5
- [ ] Region: ca-central-1
- [ ] Was the solution modified from the version published on this repository? NO
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? N/A
- [ ] Were there any errors in the CloudWatch Logs? YES

**Screenshots**
![QnABot-Exception](https://github.com/aws-solutions/qnabot-on-aws/assets/89930852/126bde27-4f5a-43eb-8aa6-dd3ceca4e45b)

**Additional Notes**
The same exception happens if the response bot (i.e. QnAAge) doesn't provide a message back. To test you can open the bot and delete the message "OK." located in the "Closing Response" of the "AgeIntent".

**Comment by dougtoppin** [comment]
Thanks for reporting this. We will review and get back to you.

**Comment by bios6** [comment]
Hi @jeve7 ,

Just to confirm are you not using the default ```ok .```  in here? :   
  https://github.com/aws-solutions/qnabot-on-aws/blob/a4828a0fbbffee53146b6244e3b47dd6af8dca84/lambda/fulfillment/lib/middleware/lexRouter.js#L352
  
 I believe if you have that enabled in your setting that should work for your specific case (since then the message won't be empty). We would expect some default response message as mentioned in the comment above. I do see some cases where this might still error out and we will add better conditioning and error handling for that in the next release.

**Comment by jeve7** [comment]
In my case "ELICIT_RESPONSE_DEFAULT_MSG" is empty as all responses are provided by the bot or the questions directly; in 5.4.5 it works fine. I changed it to something in my 5.5 environment and the exception goes away which is great. I'll check the impact of this in the presentation of our questions, good to know that there's a workaround. Thanks for the help!

**Comment by bios6** [comment]
In our next major release we will do a better error handling of this. Thanks!

**Comment by bios6** [comment]
We have just released our new major version which contains the better error handling for this. Thanks!
