### ISSUE TITLE
CF templates fail to build with v5.5.0

### ISSUE THREAD

**Issue by amendlik** [aws-solutions/qnabot-on-aws#690]
**Describe the bug**
When building v5.5.0, an error is emitted during the CloudFormation template builds:
```
dev/master failed:SyntaxError: Unexpected token '...'
dev/public failed:SyntaxError: Unexpected token '...'
```

**To Reproduce**
1. Check out v5.5.0
2. Run `npm run build`

**Expected behavior**
`master.json` and `public.json` should appear in the `build/templates/` directory.

**Please complete the following information about the solution:**
- [x] Version: **v5.5.0**
- [x] Region: **us-west-2**
- [x] Was the solution modified from the version published on this repository? **No**
- [x] If the answer to the previous question was yes, are the changes available on GitHub? **N/A**
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? **N/A**
- [x] Were there any errors in the CloudWatch Logs? **N/A**

**Additional context**
Testing using Node.js 18 and 20

**Comment by fhoueto-amz** [comment]
Thanks, we will have a look and revert back to you.

**Comment by bios6** [comment]
Hi @amendlik , 

I just cloned this github repo and followed the readme and was able to successfully deploy in us-west-2. master.json and public.json do appear in the build/templates/ directory for me.  I would recommend following the readme and also as a note npm run build is not a command that we list there. 

Thanks!

**Comment by amendlik** [comment]
Thanks for checking it. It ended up being a syntax error on my end.
