### ISSUE TITLE
Seamless switching in between specialty bots

### ISSUE THREAD

**Issue by ARUNIMA1314** [aws-solutions/qnabot-on-aws#695]
Currently, in order to switch from one specialty bot to another, first we need to type in a phrase like exit, quit or bye, and then, type in a triggering phrase to start routing to another bot. This is a little inconvenient since users most likely wouldnt chat with a chatbot and type exit and then ask queries for another category. I tried to achieve seamless switching by adding a exit_routing intent in my specialty lex v1 bots and adding a fulfillment lambda in that intent, so that whenever the user enters an utterance matching with that intent, the routing is stopped and also that utterance would work as a triggering phrase to start routing to another bot. I'm able to stop the routing in the current bot but routing to the other bot is not working. How can I do this?

**Comment by fhoueto-amz** [comment]
We will analyze this for prioritization and keep you updated.

**Comment by abhirpat** [comment]
Hi @ARUNIMA1314, this issue should be addressed with the latest release v6.0.0 from changes in #726. To provide you with additional details of this mechcanism, if you notice on line 475, the dialog state of `Fulfilled` or `Close` will exit and provide welcomeBackMessage message. I'd recommend to try this functionality in 6.0.0 and let us know if you still have any questions or concerns. For now, I will archive this issue.

Please refer to [CHANGELOG](https://github.com/aws-solutions/qnabot-on-aws/blob/main/CHANGELOG.md) for additional details about this release. Thank You!
