### ISSUE TITLE
How to modify the scoring function?

### ISSUE THREAD

**Issue by edugp** [aws-solutions/qnabot-on-aws#70]
In the [blogpost](https://aws.amazon.com/blogs/machine-learning/creating-a-question-and-answer-bot-with-amazon-lex-and-amazon-alexa/), they mention the scoring is based both the question and the answer fields, giving more weight to any matches found in the question field. How can I tune this weighting? Or if I add additional fields, how can I include them in the scoring function?

**Comment by JohnCalhoun** [comment]
related to #121
