### ISSUE TITLE
a Terraform version

### ISSUE THREAD

**Issue by LucMacPaquet** [aws-solutions/qnabot-on-aws#703]
A lot of our clients are using Terrqform as their IAC solution. 

Could you create a Terraform version or your solution ?

Thanks

**Comment by dougtoppin** [comment]
@LucMacPaquet thanks for your suggestion, we will evaluate it and get back to you

**Comment by ajaysw** [comment]
Hi @LucMacPaquet - unfortunately we don't support Terraform. However, there are tools available to convert CFT to Terraform. Thank you for your interest.
