### ISSUE TITLE
[Bug] AWS environment variable for region is wrongly set

### ISSUE THREAD

**Issue by sleepwithcoffee** [aws-solutions/qnabot-on-aws#714]
**Describe the bug**

`process.env.AWS_DEFAULT_REGION` is set to `config.profile` in various places.

**To Reproduce**

These misconfigurations can be found under:
* bin/build.js
* bin/check.js
* bin/exports.js
* bin/launch.js
* bin/name.js
* website/config/webpack.config.js

**Expected behavior**

`process.env.AWS_DEFAULT_REGION` should be set to `config.region` instead

**Please complete the following information about the solution:**
- Version: 5.5.1

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

![image](https://github.com/aws-solutions/qnabot-on-aws/assets/3896985/8ecec4dd-048a-487a-a686-2eac9e4b906a)

**Comment by dougtoppin** [comment]
@sleepwithcoffee Thanks for your report, we will investigate and get back to you

**Comment by fhoueto-amz** [comment]
Fixed in v6.0.0
