### ISSUE TITLE
Enable Intent Trigger every start of a session

### ISSUE THREAD

**Issue by dangollayan** [aws-solutions/qnabot-on-aws#715]
As of now we have these two:
WebAppConfBotInitialText: Initial text sent by the bot every session started
WebAppConfBotInitialUtterance: Initial utterance sent to the bot every session started (forces an intent to trigger)

Currently, the **WebAppConfBotInitialText** parameter is utilized to send an initial message from the bot at the start of each session. However, there's a need for this initial text to trigger an intent without requiring a separate initial utterance to be sent by the user.

**Use Case:**
Our use case requires prompting the user for their name at the beginning of each session. By setting the initial text as an intent, we can ensure that this prompt consistently appears at the start of every conversation, without relying on a user-sent initial utterance.

Is there a way to do this?

**Comment by fhoueto-amz** [comment]
Hi @dangollayan 
I am not aware of such setting. You may want to post this question to the https://github.com/aws-samples/aws-lex-web-ui project as the chat client is coming from that project.

**Comment by dangollayan** [comment]
thank you so much @fhoueto-amz , you may close this.
