### ISSUE TITLE
Using Elicit Response but with chaining 

### ISSUE THREAD

**Issue by dangollayan** [aws-solutions/qnabot-on-aws#716]
Without chaining, it is working good
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/113376990/f3dcec8b-e8ab-455a-9242-7c1ffec753a1)
But if I tried it with chaining, it goes like this
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/113376990/9caeedf6-067b-4c46-ad4b-0bba4fe8457e)

How can I avoid to proceed to chaining if it maxes out the retries, the use of chaining is that it uses the name _Elicit Response: Response Session Attribute_  to the chained document.

Expected output (with chaining)
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/113376990/f3dcec8b-e8ab-455a-9242-7c1ffec753a1)

**Comment by fhoueto-amz** [comment]
Hi @dangollayan 
Please provide the details step to reproduce (i.e. describe your config step by step) so that we can reproduce and investigate otherwise it is tough to make sure we are talking of the same thing.
Rgds
Fabien

**Comment by fhoueto-amz** [comment]
In general please use the bug template to submit a bug to ensure you provide all required info

**Comment by fhoueto-amz** [comment]
@dangollayan - Have you tried to follow the documentation for chaining?
https://docs.aws.amazon.com/solutions/latest/qnabot-on-aws/configuring-the-chatbot-to-ask-the-questions-and-use-response-bots.html - see section "Advancing and branching through a series of questions"
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/99417891/459d790d-6891-410f-b488-3f2116501db4)

**Comment by fhoueto-amz** [comment]
@dangollayan can this be closed now?
