### ISSUE TITLE
Confirmation Decline Response Prompt not sending

### ISSUE THREAD

**Issue by dangollayan** [aws-solutions/qnabot-on-aws#717]
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/113376990/816b0914-bd96-42e6-9d1a-4f8441e2ecb4)

I tried using Elicit Response in the qna bot designer where the built in I used is QNAName

When I pressed no in the confirmation it displayed the **_ELICIT_RESPONSE_RETRY_MESSAGE_** instead of the confirmation decline prompt

![image](https://github.com/aws-solutions/qnabot-on-aws/assets/113376990/f8a65cf7-e98b-4fb3-ab10-8f166596c570)
Here I tried using the lex directly and it sends the confirmation decline prompt

**Comment by fhoueto-amz** [comment]
Hi @dangollayan 
Which version of the solution are you using. In general, please use the bug template to submit issues so that we have all required info
Rgds
Fabien
