### ISSUE TITLE
Lambda layer changes not reflecting

### ISSUE THREAD

**Issue by lhknim** [aws-solutions/qnabot-on-aws#725]
**Describe the bug**
Had few change done on layers but as per "npm run update" command when we redeploy the layer changes are not reflecting .

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
The change in layer eg: lambda/es-proxy-layer/lib/fulfillment-event/runLlmQa.js  after running "npm run update" and redeploying the master stack should make the changes in the file to appear in the es-proxy-layer version 1 . Mostly this layer is used in 11 lambda functions. 

**Please complete the following information about the solution:**
- 5.5.0

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [ ] Region: e.g. us-east-1
- [ ] Was the solution modified from the version published on this repository? Yes
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? No
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs? No

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by dougtoppin** [comment]
@lhknim Thank you for your report. We will investigate and get back to you

**Comment by fhoueto-amz** [comment]
Hi
We have not seen any such issues on our side.  You can refer to the [readme ](https://github.com/aws-solutions/qnabot-on-aws/blob/main/README.md) to make sure you have all steps correct. Rerun the bootstrap if needed.

**Comment by fhoueto-amz** [comment]
@lhknim did rerunning the bootstrap help?

**Comment by fhoueto-amz** [comment]
Closing this issue. Please reopen if needed
