### ISSUE TITLE
Amazon Polly voice name for Austrian German is incorrect

### ISSUE THREAD

**Issue by malte-aws** [aws-solutions/qnabot-on-aws#728]
**Describe the bug**
The deployment of the Bot fails with `de_AT` as one of the languages in the LexV2BotLocaleIds parameter. 

```Received response status [FAILED] from custom resource. Message returned: An error occurred (ValidationException) when calling the CreateBotLocale operation: Vicki and neural are not valid values for Voice Id and Engine respectively. (RequestId: e940f672-36f8-4e73-983d-8caa54063a5b)```

**To Reproduce**
Deploy the CloudFormation template of this solution and use `de_AT` as the LexV2BotLocaleIds parameter.

**Expected behavior**
The deployment should use the correct voice name for the neural engine.

**Please complete the following information about the solution:**
- [x] Version: v5.5.2

- [x] Region: us-east-1
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [x] Were there any errors in the CloudWatch Logs? Yes, error in CloudFormation Events.

**Comment by fhoueto-amz** [comment]
Thanks for reporting this and submitting the PR. We will look into this

**Comment by tmekari** [comment]
Hi @malte-aws, we have addressed this issue and it will be available in our upcoming release.

**Comment by malte-aws** [comment]
Hi,

thank you.

**Comment by fhoueto-amz** [comment]
Fixed in v6.0.0
