### ISSUE TITLE
Answer data that contains only double-byte full-width characters cannot be imported.

### ISSUE THREAD

**Issue by FdaiJ** [aws-solutions/qnabot-on-aws#731]
**Describe the bug**
An error occurs when importing an Excel file containing answer data that is created using only double-byte full-width characters.

**To Reproduce**
An error occurs when importing an Excel file created with answer data using only Japanese full-width 2-byte characters.
Please import using the attached Excel file.
・Import results
QnABot.keyword1 to QnABot.keyword5 are NG
QnABot.keyword6 to QnABot.keyword10 are OK
・NG error message
Error Loading Content
Warning: No answer found for QID:"QnABot.keyword1". The question will be skipped.
Warning: No answer found for QID:"QnABot.keyword2". The question will be skipped.
Warning: No answer found for QID:"QnABot.keyword3". The question will be skipped.
Warning: No answer found for QID:"QnABot.keyword4". The question will be skipped.
Warning: No answer found for QID:"QnABot.keyword5". The question will be skipped.
・Difference between NG and OK
NG answer data contains only full-width 2-byte characters
OK answer data contains 1-byte characters

**Expected behavior**
You can import answer data containing only Japanese full-width 2-byte characters.

**Please complete the following information about the solution:**
- [ ] Version: 5.5.1
[ConversationDataForKeywordSearch_20240528.xlsx](https://github.com/aws-solutions/qnabot-on-aws/files/15458206/ConversationDataForKeywordSearch_20240528.xlsx)

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [ ] Region: ap-northeast-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? No

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by fhoueto-amz** [comment]
Thanks for reporting this, We will look into it.

**Comment by michaelin-96** [comment]
Hi @FdaiJ,

This issue will be resolved in the next release. 

However if you need to make changes to your local deployment to ingest double-byte characters, you can do the following:
Replace 
`if (!question.a || question.a.replace(/[^a-zA-Z0-9-_]/g, '').trim().length == 0) {`
to 
`if (!question.a || question.a.replace(/\s/g, '').length == 0) {`

In convert-xlsx.js (Ln 175) & import.vue (Ln 398 & 437). This will allow you to import xlsx & json with double-byte chars only.

Closing this ticket out. Thanks
