### ISSUE TITLE
Shell and other commands not working in Ubuntu linux

### ISSUE THREAD

**Issue by bchunduri** [aws-solutions/qnabot-on-aws#734]
Team,

We use Ubuntu (Ubuntu 22.04.2 LTS) linux machine to bootstrap the QnA bot solutions and render the stack templates to suit our environment. 

The bootstrap fails at quite a few places as described below:

1. The first line of the main **Makefile** contains _shell_ command which do not exists in Ubuntu and it is more like a MacOS command shell. Please fix this so can support for any OS (MacOS, Windows, Linux) >> As an alternative we have amended the logic with a **for** loop.

2. The pushd & popd commands in the file **ml_model/embedding/package-model.sh** fails though exists in the Linux, the reason is could be the **sh** shell it is using in the **ml_model/embedding/Makefile** that was incorrect >> Amending this with **zsh** worked where pushd and popd found in zsh or ksh shell.

Appreciate your review and fix on the above.

**Comment by dougtoppin** [comment]
@bchunduri Thanks for your report. We will evaluate it and get back to you.

**Comment by abhirpat** [comment]
related PR #736

**Comment by fhoueto-amz** [comment]
the file ml_model/embedding/package-model.sh has been deprecated.

**Comment by fhoueto-amz** [comment]
Unfortunately, we support only Amazon Linux for now and have not seen enough uptake to support Ubuntu. I will close this ticket. You can submit an enhancement request if you for consideration in the roadmap if needed.
