### ISSUE TITLE
ELICIT_RESPONSE_DEFAULT_MSG can't be changed

### ISSUE THREAD

**Issue by seano10** [aws-solutions/qnabot-on-aws#745]
**Describe the bug**
The default value for the field ELICIT_RESPONSE_DEFAULT_MSG is "OK.".  I have tried changing it to a different value (eg "", or "W") but although I am able to save the settings the behaviour still returns "OK."  In fact it returns even if I have provided a response message, meaning that I actually get "OK. Ok, thank you", when it should just return "Ok, thank you". 

**To Reproduce**
Change the ELICIT_RESPONSE_DEFAULT_MSG in the settings tab of the QnA bot and then utilise the elicit response feature in an answer.

**Expected behavior**
I expect the returned value to include the value set in the ELICIT_RESPONSE_DEFAULT_MSG field, instead it always returns "OK."

**Please complete the following information about the solution:**
- [ ] Version: 5.5.2

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [ ] Region: [e.g. us-east-1] eu-west-2 (London)
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? yes
- [ ] Were there any errors in the CloudWatch Logs? no

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by fhoueto-amz** [comment]
Thanks, for raising this. We will analyze and revert back.

**Comment by fhoueto-amz** [comment]
@seano10 
The settings in the content designer is not well described. The Elicit_response_default_MSG setting is the default message that qna_bot will assume is coming from the elicit bot if the elicit bot closing response is empty (therefore the default in the setting name). We will clarify this in our UI and documentation. So this setting will typically not be used as the elicit bot will typically send back some closing response. To change the closing response sent back by the elicit response bot, you will need to go to your Amazon Lex console, find the elicit bot you are using, look at its conversational flow for the intent in question (see https://docs.aws.amazon.com/lexv2/latest/dg/understanding-new-flows.html). For example with the QNAName elicit bot, go to intent>nameIntent>conversation flow. On the last page, you will see the closing response (default is Ok.). If you want to modify that, edit the closing response to whatever you want, rebuild the bot, create a new version and set the live alias to the latest version (see https://docs.aws.amazon.com/lexv2/latest/dg/versions-aliases.html). The elicit bot answer will now be whatever you set in the closing response. Alternatively, you can delete the closing response, rebuild the bot, create a new version and set the live alias to the latest version. In that case,  QnA bot will use the setting Elicit_response_default_MSG for that elicit bot  as the response from that elicit bot is now empty.

**Comment by seano10** [comment]
@fhoueto-amz 
Thank you for the quick turnaround on this, I will take a look at what you suggest but that makes sense now, thanks.
