### ISSUE TITLE
Add support for Titan Models for Bedrock Knowledge Bases

### ISSUE THREAD

**Issue by anthroprose** [aws-solutions/qnabot-on-aws#746]
Inside of the AWS Console for Bedrock Knowledge Bases you can choose Titan Text G1 Premier (amazon.titan-text-premier-v1:0). Right now QNABot only has Anthropic models for KBs. Let's try and get Amazon owned model(s) added.

**Comment by abhirpat** [comment]
Thank you for raising feature request @anthroprose . We will get back to you on this.

**Comment by abhirpat** [comment]
Hi @anthroprose , these models are now available with latest release v6.1.0.

Please refer to [CHANGELOG](https://github.com/aws-solutions/qnabot-on-aws/blob/main/CHANGELOG.md) for additional details about this release. Thank You!
