### ISSUE TITLE
Logout functionality not working correctly in qnabot-on-aws solution

### ISSUE THREAD

**Issue by demismirnov** [aws-solutions/qnabot-on-aws#747]
**Describe the bug**
We have deployed the "qnabot-on-aws" solution and are facing a critical issue with the logout functionality. When a user logs out of the application, they are redirected to the Cognito login page. From there, they can log back in as an admin user without providing any credentials, simply by clicking the "Sign In as Admin" button. This indicates that the logout process is not effectively terminating the user's session, posing a significant security risk.

**To Reproduce**
1. Deploy the "qnabot-on-aws" solution.
2. Log in to the application as an admin user.
3. Click on the logout button.
4. On the Cognito login page, click the "Sign In as Admin" button.
5. Observe that the user is logged back in as an admin without providing any credentials.

**Expected behavior**
When a user logs out of the application, their session should be terminated, and they should be required to provide their credentials to log back in.

**Please complete the following information about the solution:**
- [v6.0.1] Version: [e.g. v0.0.1]
- [ us-east-1] Region: [e.g. us-east-1]
- [N] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [Y] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [N] Were there any errors in the CloudWatch Logs?

**Comment by dougtoppin** [comment]
@demismirnov Thanks for your report, we will investigate and get back to you

**Comment by michaelin-96** [comment]
Hi @demismirnov, this issue should be addressed in the v6.0.2 release. Closing task out.

**Comment by fhoueto-amz** [comment]
@demismirnov Have you deployed the version 6.0.2?

**Comment by demismirnov** [comment]
Yes we're working with 6.0.2 and not seeing the issue anymore. Thank you
