### ISSUE TITLE
QnA Bot not logging every interaction in Kibana

### ISSUE THREAD

**Issue by seano10** [aws-solutions/qnabot-on-aws#754]
**Describe the bug**
If I try to look at activity through my Connect instance and my QnA bot I find that not all conversations that hit Connect get recorded in the QnA bot stats in Kibana.  I may be doing something wrong, but there seems to be no correlation as to which conversations appear in the Kibana log and which do not

**To Reproduce**
Latent behaviour - happens all the time

**Expected behavior**
I would expect to be able to report on the number and nature of conversations in KIbana for QnA Bot and it correspond with the native Connect reporting/loggin

**Please complete the following information about the solution:**
- [ ] Version: [e.g. v0.0.1] v5.5.2

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [ ] Region: [e.g. us-east-1] eu-west-2 (London)
- [ ] Was the solution modified from the version published on this repository? - no
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? yes
- [ ] Were there any errors in the CloudWatch Logs? No

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by seano10** [comment]
For added context, between 11am & 12pm today connect shows 64 contacts, QnA bot in Kibana shows 3.  Now admittedly 37 of the contacts resulted in the customer clicking on the chat widget but never asking anything, so I wouldn't expect those to be logged, but what about the other 24??

**Comment by fhoueto-amz** [comment]
Thanks for reporting this, we will review and revert.

**Comment by seano10** [comment]
Just adding some more findings for context.  I have figured out (I think) that the only contacts that get logged through to kibana are those where the customer has to answer a follow on question, so:


Customer:  Can I bring my dog
Bot: Sorry no dogs are allowed on site
---- doesn't appear in kibana

Customer:  How much is early check-in
Bot: Early check in is £20, would you like to add this to your booking?
Customer: No
----DOES appear in kibana

Customer: What is the VIP experience
Bot:  Our VIP experience offers you the best seats in the house..... Would you like to add it to a booking?
Customer: Yes
Bot:  Ok please hold on while I connect you to an agent
----DOES appear in kibana

**Comment by seano10** [comment]
Hi, just wondering if anyone had a chance to look at this yet?

**Comment by abhirpat** [comment]
@seano10 could you please provide us sample questions you're creating so we can try to reproduce it on our end? You can achieve so by creating sample questions with non-sensitive information and export it from Tools menu in the designer.

**Comment by seano10** [comment]
@abhirpat give this sample a go.  If it works the same for you then if you ask it "are there towels in the room" it won't log in kibana, but if you ask "VIP package" and then reply "yes" when it asks if you want to add to a booking, it will appear in Kibana.

Any questions just shout
[qna_kibana_logging_issue_subset.json](https://github.com/user-attachments/files/16786069/qna_kibana_logging_issue_subset.json)

**Comment by seano10** [comment]
@abhirpat after asking the two questions above in the kibana dashboard it just shows the second one:

![image](https://github.com/user-attachments/assets/39e0d4f2-ad50-4fa5-8b53-5518a9393f21)

**Comment by seano10** [comment]
Also - further information - I have just been doing some further testing and it would appear that all questions log correctly to kibana when I test using the QnA Bot Client:

![image](https://github.com/user-attachments/assets/6b2b76ff-12cc-4996-8484-39a697b064e6)


So it appears I am only getting the problem when calling from Connect

**Comment by michaelin-96** [comment]
Hey @seano10,

I was able to create a connect instance and test in the connect console on v6.1.0. I've provided some screenshots showing that OS Dashboards is logging the utterances, even without any followup questions.

![Screenshot 2024-09-05 at 12 01 28 PM](https://github.com/user-attachments/assets/47b233ec-f22e-44f8-9cf7-3e56f8bb676b)

<img width="849" alt="Screenshot 2024-09-05 at 12 01 58 PM" src="https://github.com/user-attachments/assets/4ff6fd62-44ab-4136-9a99-8d283aa7c0e0">

Can you try to upgrade to a later version (v6.X.X) of QnABot?

**Comment by seano10** [comment]
@michaelin-96 it is fixed.  I decided to clear everything down and do a clean install rather than an update of 6.1.0 over the top, I am glad to say that this works.

Thank you for your help
Sean

**Comment by michaelin-96** [comment]
@seano10 Glad it worked and thanks for the updates. Closing.
