### ISSUE TITLE
Which S3 bucket is used for storing data in QnABot Content Designer?

### ISSUE THREAD

**Issue by preethy-1** [aws-solutions/qnabot-on-aws#755]
Could someone clarify which S3 bucket is used for storing data in the QnABot Content Designer?

**Comment by fhoueto-amz** [comment]
Hi @preethy-1 
Can you please clarify your questions? Which data are you referring to? the question bank, the static assets (cloud formation template) to deploy the solution, the content for kendra or bedrock kb?
Have you looked ta the solution implementation guide? https://docs.aws.amazon.com/solutions/latest/qnabot-on-aws/solution-overview.html

**Comment by preethy-1** [comment]
Hi @fhoueto-amz 

Thanks for the response.

I am referring to the data that we are adding to the Content Designer, such as questions and answers for QnA and text passages. I have checked the available S3 buckets but couldn't find where these data are stored. Could you please clarify which S3 bucket is being used for storing this content?

**Comment by fhoueto-amz** [comment]
Hi
The questions and answers and text passages added through the content designer are stored in opensearch not in S3.  Please refer to the published documentation  https://docs.aws.amazon.com/solutions/latest/qnabot-on-aws/solution-overview.html and precisely https://docs.aws.amazon.com/solutions/latest/qnabot-on-aws/how-qnabot-on-aws-works.html for more details

**Comment by fhoueto-amz** [comment]
The architecture overview (https://docs.aws.amazon.com/solutions/latest/qnabot-on-aws/architecture-overview.html) also explains the same
