### ISSUE TITLE
Clarification on Data Flow and LLM Roles in CloudFormation Architecture

### ISSUE THREAD

**Issue by preethy-1** [aws-solutions/qnabot-on-aws#757]
Could anyone please clarify the data flow labeled as number 9 in the architecture diagram, as it appears twice: "RAG and other fallback data sources" and "Text generation LLM"?

Additionally, could you confirm whether steps 2b, 2c and 2d in the Cloudformation stack represent the following:

2b: This is for storing Question and Answer (QnA) pairs. 

2c: When an answer is not found in the QnA OpenSearch, the system searches the passages stored in OpenSearch. We are assuming that the LLM in 2c is dedicated to the text passages stored in OpenSearch.

2d: When an answer is not found in the QnA OpenSearch, the system searches the documents stored in the Bedrock or Kendra Knowledge Base. We are assuming that the LLM in 2d is dedicated to the documents stored in the Bedrock/Kendra Knowledge Base.

**Comment by fhoueto-amz** [comment]
Hi 
for the dataflow in step 9, the first step (9a) is that the RAG and other data sources can be used as fallback if no match is returned from the OpenSearch question bank. The second step (9b) is that when using that fallback mechanism, you can additionally ask the solution to use the text generation LLM can to create the search query and to synthesize a response from the returned document excerpts by setting the LLM_QA_ENABLE parameter to true in the content designer setting. This is why you have 2 numbers 9 in the flow. You can refer to https://docs.aws.amazon.com/solutions/latest/qnabot-on-aws/architecture-overview.html for a description of each step of the data flow.

For the cloudformation,
Step 2a are parameters related to the QnA pairs stored in Opensearch which is the core functionality of the solution. Step 2b is for enabling embeddings to be used to match questions  in Opensearch (if embeddings  is not enaled, you do a direct search for the questions). Step 2c enables using a LLM to rewrite questions which are then matched using embeddings defined in 2b and additionally potential usage of LLM to rewrite excerpts  from the RAG and other fallback data sources like passage when the answer is coming from those  RAG and other fallback data sources (see 9b in the answer to your first question)
Step 2d is for providing the Kendra or Bedrock fallback datasources mentioned in step 2c if you want to use them. Note that passages in opensearch  can be considered as always on fallback if you provide them. But the query and answer from those passages will depend on what is activated in step 2b and 2c.

**Comment by preethy-1** [comment]
Thanks @fhoueto-amz
