### ISSUE TITLE
Large Dataset not Rendering in Designer UI

### ISSUE THREAD

**Issue by MatthewLoller** [aws-solutions/qnabot-on-aws#758]
**Describe the bug**
I have a very large data set I imported from a prior 5.5.0 version, about 750 records. The UI shows no data in the list. When I add a new record it appears and is saved to Opensearch, however when I refresh the page that record also disappears because it is reloading all of the records. In dev tools I can see the records correctly coming back from Opensearch and API Gateway.

**To Reproduce**
Attempt to load a very large dataset in the designer UI

**Expected behavior**
I expect to paginate through all of my records.

**Please complete the following information about the solution:**
- [ v6.0.2] 

- [ us-east-1 ] Region: [e.g. us-east-1]
- [ x ] Was the solution modified from the version published on this repository? Yes, some fulfillment code modified
- [ x ] If the answer to the previous question was yes, are the changes available on GitHub? No
- [ x ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [ x ] Were there any errors in the CloudWatch Logs?

**Comment by fhoueto-amz** [comment]
Hi 
Thanks for reporting this.
Can you please share either the relevant cloudwatch logs and a dataset to reproduce if possible? (question and settings)
Have you tried to decrease the number of items per page to 50 or lower instead of the max?
Rgds
Fabien

**Comment by abhirpat** [comment]
Hi @MatthewLoller you mentioned that the records correctly coming back coming correctly in dev tools. So do you see any errors in the frontend? Could you please also check Developer Tools > Console and Network tabs?

**Comment by MatthewLoller** [comment]
@abhirpat The root cause of this issue appears to be the Vertical tab character being saved with the questions. Upon deeper inspection we were able to find an asci char in the opensearch index. When it was coming back to the UI, the map couldn't parse it.
