### ISSUE TITLE
The reply of the qna bot is sometimes null/blank (intermittent)

### ISSUE THREAD

**Issue by dangollayan** [aws-solutions/qnabot-on-aws#759]
**Describe the bug**
The qna bot sometimes replies a blank reply/ null when using lambda hook.
![image](https://github.com/user-attachments/assets/b7559ebd-0af2-4ceb-862b-d2c2211a7777)

**To Reproduce**
Create an agent with knowledgebase/action group as a lambda hook then attached it to no hits intent
![image](https://github.com/user-attachments/assets/5358b90e-883a-40d9-8f98-32f784dc89a0)

**Expected behavior**
The bot should be able to reply with what the lambdah hook returned

**Please complete the following information about the solution:**
- [v6.0.2 ] 
- [ us-east-1] 
- [ no] Was the solution modified from the version published on this repository?
- [no ] If the answer to the previous question was yes, are the changes available on GitHub?
- [yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ no] Were there any errors in the CloudWatch Logs?

**Screenshots**
no errors in fulfillment lambda as well
![image](https://github.com/user-attachments/assets/1c0c92db-2450-47f7-9af7-4378f06d3456)

**Comment by dangollayan** [comment]
Hi, I've just finished troubleshooting and noticed that if the Lambda hook process exceeds 30 seconds, it returns a blank reply. Can anyone help with this issue?

**Comment by bobpskier** [comment]
@dangollayan If I'm not mistaken, LexV2 has a 30 second timeout on RecognizeText fulfillment. If the QnABot fulfillment processing exceeds this time (including lambda hook) then LexV2 will timeout the request. I believe there are some default messages that can be configured for this case in LexV2. Also, depending on your lexv2 client, the calls to LexV2 might be able to send in a streaming based request although I'm not sure how QnABot would handle this. I think the default for a timeout can be longer using streaming. I've never experimented with streaming for example from the LexWebUi AWS sample to QnABot but perhaps this would give you a chance to stream some messages while the processing is taking place on the back end lambda hook.

**Comment by dangollayan** [comment]
> @dangollayan If I'm not mistaken, LexV2 has a 30 second timeout on RecognizeText fulfillment. If the QnABot fulfillment processing exceeds this time (including lambda hook) then LexV2 will timeout the request. I believe there are some default messages that can be configured for this case in LexV2. Also, depending on your lexv2 client, the calls to LexV2 might be able to send in a streaming based request although I'm not sure how QnABot would handle this. I think the default for a timeout can be longer using streaming. I've never experimented with streaming for example from the LexWebUi AWS sample to QnABot but perhaps this would give you a chance to stream some messages while the processing is taking place on the back end lambda hook.

thanks for your thoughts @bobpskier!

**Comment by fhoueto-amz** [comment]
Hi @dangollayan 
Here is the link to the documentation of the timeout limit https://docs.aws.amazon.com/lexv2/latest/APIReference/API_runtime_RecognizeText.html.
We will clarify in our documentation

**Comment by dangollayan** [comment]
> Hi @dangollayan Here is the link to the documentation of the timeout limit https://docs.aws.amazon.com/lexv2/latest/APIReference/API_runtime_RecognizeText.html. We will clarify in our documentation

hi @fhoueto-amz, can you elaborate how can we do this to QNA bot setup?

**Comment by michaelin-96** [comment]
@dangollayan

I would start here for the Lex API reference docs: https://docs.aws.amazon.com/lexv2/latest/dg/streaming-progress.html#progress-updates. Seems like you can specify a timeout length of up to 15 minutes (900 seconds)

**Comment by dangollayan** [comment]
> @dangollayan
> 
> I would start here for the Lex API reference docs: https://docs.aws.amazon.com/lexv2/latest/dg/streaming-progress.html#progress-updates. Seems like you can specify a timeout length of up to 15 minutes (900 seconds)

Doesn't work with the solution

**Comment by abhirpat** [comment]
Hi @dangollayan , 

Before proceeding to this solution, you will want to evaluate if there is negative impact of this change in terms of lambda concurrency limits and lambda 15 min timeout .

 If you still decide to proceed, I'd suggest to try post-processing lambda hook and examine the input event to the lambda. In that input event, you can modify sessionState as needed to set [timeToLive](https://docs.aws.amazon.com/lexv2/latest/APIReference/API_runtime_ActiveContext.html#lexv2-Type-runtime_ActiveContext-timeToLive). 

For more information on post-processing lambda hooks, please see [Lambda Hooks](https://github.com/aws-solutions/qnabot-on-aws/tree/main/source/docs/lambda_hooks)

Best,
Abhishek

**Comment by abhirpat** [comment]
Hi @dangollayan, I'll go ahead and archive but please feel free to let me know if any follow-up questions

**Comment by dangollayan** [comment]
> @dangollayan If I'm not mistaken, LexV2 has a 30 second timeout on RecognizeText fulfillment. If the QnABot fulfillment processing exceeds this time (including lambda hook) then LexV2 will timeout the request. I believe there are some default messages that can be configured for this case in LexV2. Also, depending on your lexv2 client, the calls to LexV2 might be able to send in a streaming based request although I'm not sure how QnABot would handle this. I think the default for a timeout can be longer using streaming. I've never experimented with streaming for example from the LexWebUi AWS sample to QnABot but perhaps this would give you a chance to stream some messages while the processing is taking place on the back end lambda hook.

Tried the lex web UI streaming, it works like chat gpt, but the still the cap is 30 seconds

**Comment by dangollayan** [comment]
> Hi @dangollayan ,
> 
> To answer your questions, I'd suggest to try post-processing lambda hook and examine the input event to the lambda. In that input event, you can modify sessionState as needed to set [timeToLive](https://docs.aws.amazon.com/lexv2/latest/APIReference/API_runtime_ActiveContext.html#lexv2-Type-runtime_ActiveContext-timeToLive). Before implementing this solution, you will want to evaluate if there is negative impact of this change in terms of concurrency and lambda 15 min timeout .
> 
> For more information on post-processing lambda hooks, please see [Lambda Hooks](https://github.com/aws-solutions/qnabot-on-aws/tree/main/source/docs/lambda_hooks)
> 
> Best, Abhishek

Hi @abhirpat,

Thanks for examining my problem, sorry but I don't get your point. Are you suggesting that instead of using utterance lambda hook, I should my lambda to post-process lambda hook?

**Comment by abhirpat** [comment]
Hi @dangollayan Sorry, I don't recall having a discussion about Utterance Lambda in this thread. Perhaps, you were discussing about it on other threads.

For your question on modifying sessionState, I recommended to explore post-processing lambda hooks to modify request as per your needs need. If you haven't had a chance to explore lambda hooks before, I'd recommend to explore both pre-processing  and post-processing lambda hooks. You can set these up and print input event to the these lambda to see what keys in the request you can access and modify. These lambda hooks gives you flexibility to manipulate input and output of chat user's request to QnABot.

To learn more on setup about lambda hooks, please see [Lambda Hooks](https://github.com/aws-solutions/qnabot-on-aws/tree/main/source/docs/lambda_hooks)
