### ISSUE TITLE
Changing Bedrock knowledge base model without Stack update

### ISSUE THREAD

**Issue by preethy-1** [aws-solutions/qnabot-on-aws#762]
Could anyone please reply if there is a way to change the Bedrock KB model id without updating the stack?

**Comment by fhoueto-amz** [comment]
Hi @preethy-1 
you will  need to update the stack.

**Comment by abhirpat** [comment]
Hi @preethy-1 , it's not made available by default but you can define it as a Custom Setting setting by clicking on "Add New Setting" in the Settings page and then input KNOWLEDGE_BASE_ID. You can check in the fulfillment logs if the this ID is accurately reflected or not.

**Comment by user-preethy** [comment]
Hi @abhirpat, Currently I am using Claud instant v2.1 in bedrock knowledge base. Can I switch it to Claude 3 Sonnet in the same way?

**Comment by abhirpat** [comment]
You should be able to using KNOWLEDGE_BASE_MODEL_ID. Please try in same manner as I explained above.
