### ISSUE TITLE
QnABot version 6.1.0 breaks creating buttons in appContext for lex-web-ui when greater than 5 buttons are configured

### ISSUE THREAD

**Issue by bobpskier** [aws-solutions/qnabot-on-aws#765]
**Describe the bug**
QnABot in lex.js used to automatically create the proper structure in the session attribute, appContext, to support greater than 5 buttons when using lex-web-ui. The function copyResponseCardtoSessionAttribute(response) was removed in 6.1.0. Why? This allowed easy support of greater than 5 buttons which is common when using QnABot even with LexV2. Users could add more than five buttons in the designer UI and they would render in lex-web-ui. Such a silly limitation in lex but QnABot was able to work around it however this feature was removed from QnABot. 

**To Reproduce**
Install 6.1.0. Create a question and answer with 6 buttons. The six buttons are no longer passed in appContext as they were in prior versions of QnABot. 

**Expected behavior**
Six or more buttons are passed in appContext such that lex-web-ui can render them. 

**Please complete the following information about the solution:**
- [ 6.1.0]

**Additional context**

**Comment by fhoueto-amz** [comment]
Thanks Bob, we will look into this

**Comment by michaelin-96** [comment]
@bobpskier Thanks for bringing this to our attention. This will be fixed in the next upcoming patch release v6.1.1

**Comment by bobpskier** [comment]
@michaelin-96 Thanks!
