### ISSUE TITLE
Cannot save an item with no Response Card, if you accidentally clicked on card Title or Card Image URL 

### ISSUE THREAD

**Issue by rstrahan** [aws-solutions/qnabot-on-aws#77]
## Actual Behavior

When adding a new item, if you open 'Advanced', the UI indicates that 'Card Title' and 'Card Image URL' are Required.  This is not accurate. They can be left empty is there is no card for the item.
However, if you click on either one of these fields at all, there is no going back.. the field suddenly becomes Required - if there is no way to save the item without cancelling.

![image](https://user-images.githubusercontent.com/10953374/39473197-8eecd0c0-4d1b-11e8-83e6-44cd16248592.png)

## Expected Behavior

Cards are *not* required for an item. However, if a Card is defined, then both fields must be entered.
If user clicks (perhaps accidentally) on one of these fields, they should still be able to save the item with the fields blank. 

## Steps to Reproduce the Problem

  1. Add new item. Complete standard fields (ID, Question, Answer)
  2. Open Advanced. Click in the Card Title field
  3. try to save item without adding a card

**Comment by pdkn** [comment]
A workaround to this is, after clearing the field (i.e Card Image Url), 
1: focus a different field
2: click the disabled 'Update' button ( it becomes enabled).
3: Then click 'Update" again to save.

If that doesn't work, change the value of another field, try button again. then go back to record and reset the other field back
