### ISSUE TITLE
Displaying Messages and Response Cards Sequentially in a Chatbot

### ISSUE THREAD

**Issue by preethy-1** [aws-solutions/qnabot-on-aws#770]
Hi,
How can I display a message followed by a response card (like buttons) and then another message in a chatbot? I would like the flow to appear as follows:

Test message 1
Response Card (Buttons)
Test message 2

I want the second message to display without requiring the user to click the buttons.

**Comment by fhoueto-amz** [comment]
Thanks for submitting this, we will revert back

**Comment by fhoueto-amz** [comment]
Hi @preethy-1 How is this different from https://github.com/aws-solutions/qnabot-on-aws/issues/727

**Comment by preethy-1** [comment]
Hi @fhoueto-amz 
Thanks for your response.
I'm looking for something like this,

Here are the topics:
Button1
Button 2
Is there anything else?

I want to display a message followed by buttons, and after the buttons, the next message should appear. However, when I tried, this is what happens:

Here are the topics: Is there anything else?
Button1
Button 2

**Comment by fhoueto-amz** [comment]
Can you make a sample set of questions to reproduce this and attach them
