### ISSUE TITLE
QNA Bot with bedrock knowledgebase and connect feature.

### ISSUE THREAD

**Issue by dangollayan** [aws-solutions/qnabot-on-aws#773]
**Describe the bug**
The bot sometimes returns a blank response when using the Bedrock knowledge base as a fallback feature.

**To Reproduce**
Ask the bot a question that triggers the Bedrock knowledge base fallback feature.

**Expected behavior**
The bot should display the results retrieved from the Bedrock knowledge base.

**Please complete the following information about the solution:**
- [v6.1.1] Version:

- [ap-southeast-2] Region
- [No] Was the solution modified from the version published on this repository?
- [N/A] If the answer to the previous question was yes, are the changes available on GitHub?
- [Yes ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [No] Were there any errors in the CloudWatch Logs?

**Screenshots**
Sample screenshot of empty response
![image](https://github.com/user-attachments/assets/23e11b7e-1440-42e3-b0f0-19f754e1873b)
Logs of empty response:
![image](https://github.com/user-attachments/assets/08a8b590-1c34-48fb-af2d-ed90544aa984)
Connect flow I used:
![image](https://github.com/user-attachments/assets/6c1184d4-8ca2-4f0c-8de1-d818d6ca7b82)

**Additional context**
Based on testing and log analysis, the response is blank if the Bedrock knowledge base processing time exceeds 6-7 seconds.

**Comment by fhoueto-amz** [comment]
Thanks. We will revert back.

**Comment by abhirpat** [comment]
Hi @dangollayan, thank you for reporting this. To help further investigate it -

1.  You mentioned you see response blank in connect. Could you please try comparing in QnABot's chat client? Does it show blank as well?
2. Also, in your logs, could you also please provide an expansive screenshot of that says "final". It's the final response that is sent to clients that we need to look at.
3. Have you checked logs from connect chat side to see if there any errors? You can also try to see browser console logs in chrome developer tools and network logs.

**Comment by abhirpat** [comment]
Hi @dangollayan wanted to check-in to see if you had a chance to see my previous message.

**Comment by dangollayan** [comment]
> Hi @dangollayan wanted to check-in to see if you had a chance to see my previous message.

Hi, sorry for the late response and thank you for looking out for our problem

1. Yes, it shows blank also
2. in the screenshot I sent, in the cloudwatch logs, there's "final:" part
3. I'll get back to you ASAP

**Comment by abhirpat** [comment]
Hi @dangollayan, checking-in again if you have any further updates on the information I requested. If you could reproduce and provide -
1. Thanks
2. I'll need expanded view of "final" (click dropdown on that line please) so I can look at the response.
3. Also, on the frontend chat client side, I need to see browser console logs in chrome developer tools and network logs.

**Comment by fhoueto-amz** [comment]
closing this ticket
