### ISSUE TITLE
Issue with Bedrock Fallback Returning Incorrect Response from OpenSearch

### ISSUE THREAD

**Issue by preethy-1** [aws-solutions/qnabot-on-aws#775]
Hi,

We have integrated the Bedrock knowledge base into our QnA solution. In the logs, we noticed that Bedrock's response was "Sorry, I don't know that...". However, the chatbot client returned an answer from an intent stored in OpenSearch. We understand that Bedrock serves as the fallback mechanism, but it appears that after Bedrock search, the system is querying OpenSearch again, leading to an incorrect response being provided to the user. Our requirement is that if the answer is not found in Bedrock, the user should receive "Sorry, I don't know that..." instead of another response from OpenSearch.
![image](https://github.com/user-attachments/assets/677b9538-8028-40df-b7bc-2c46d5196d4a)

**Comment by fhoueto-amz** [comment]
@preethy-1 
The no_hit response is a configuration in the designer (a question that you specifically set - see https://docs.aws.amazon.com/solutions/latest/qnabot-on-aws/using-keyword-filters-for.html#custom-dont-know-answers) to allow you to control the message you are responding when there is no-hits. You just need to set that question and it should be the answer the user gets when there is no match. If the question is not configured you get a default answer
