### ISSUE TITLE
Site to site VPN IPsec Tunnel

### ISSUE THREAD

**Issue by anjugds** [aws-solutions/qnabot-on-aws#779]
hi @abhirpat and @fhoueto-amz 
   Can we use IPsec Tunnel site to site VPN to connect to Dashboard from the Customer Network. If so is there anything to consider?

We have our chatbot deployed in VPC and inside OpenSearch inside the private subnet.

Regards,
Anju

**Comment by abhirpat** [comment]
Hi @anjugds , when using VPC template it deploys OpenSearch and OpenSearch Dashboards within a VPC's Private Subnets. By default, there are no means of accessing OpenSearch Dashboards within the VPC's Private Subnets. Thus, in theory, you will need to use a Tunnel to make a connection to this network. We have a guidelines on this using SSH SOCKS5 Tunnel but you can further try exploring with  IPsec Tunnel. To learn more, please see [Accessing OpenSearch Dashboards in VPC](https://github.com/aws-solutions/qnabot-on-aws/tree/main/source/docs/VPC_support#accessing-opensearch-dashboards-in-vpc)

**Comment by anjugds** [comment]
hi @abhirpat,

    We know this connection by creating EC2. But here client wants to have a connection from their Network to this dashboard using IPsec tunnel. Please let us know if their is any limitations considering the chatbot.
Regards,
Anju

**Comment by abhirpat** [comment]
Hi @anjugds, the QnABot utilizes AWS OpenSearch, which provisions OpenSearch Dashboards. To learn more about its limitations, you'll find it in OpenSearch documentation. Here is a reference, please check this reference: [How can I use Amazon Cognito authentication to access OpenSearch Dashboards from outside of a VPC?](https://repost.aws/knowledge-center/opensearch-dashboards-vpc-cognito)

This link provides details about OpenSearch Dashboards, VPC, and Cognito integration, which should help address your concerns about limitations. [[1]](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/ingestion-limitations.html). Additional Reference - [AWS OpenSearch Documentation](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/vpc-interface-endpoints.html)

Please let me know if you need any further clarification or have additional questions.

Thank you,
Abhishek

**Comment by anjugds** [comment]
Thank you!
