### ISSUE TITLE
Metadata filter using an attribute from bot user

### ISSUE THREAD

**Issue by preethy-1** [aws-solutions/qnabot-on-aws#780]
Hi @abhirpat,

How can I make use of the domain data passed from the parent web application to chatbot to apply metadata filtering in Amazon Bedrock Knowledge base for RAG. 
For eg: 
if domain data is "banking", then filter should only pickup document sources having metadata attribute domain as "banking"

**Comment by fhoueto-amz** [comment]
closing this
