### ISSUE TITLE
Missing variable in OpenSearch dashboard

### ISSUE THREAD

**Issue by preethy-1** [aws-solutions/qnabot-on-aws#785]
Hi,

We have added the variable, username to the session, but this is not being passed to the OpenSearch dashboard. While we can see other variables, the ones we added are missing. How can we retrieve these values in the OpenSearch dashboard? Additionally, is it possible to achieve this by modifying the es-logging.js file in the EsProxy layer?
![image](https://github.com/user-attachments/assets/eda9f184-fef5-41cc-9d31-fab48c5ce09f)

**Comment by abhirpat** [comment]
Hi @preethy-1,
Yes, you can modify the data that needs to be sent in es-logging.js [here](https://ask.qbusiness.aws.dev/github.com/aws-solutions/qnabot-on-aws/blob/feature/v6.1.5/source/lambda/es-proxy-layer/lib/es-logging.js). However, it does show session info in there. 

![Screenshot 2024-11-25 at 8 41 36 AM](https://github.com/user-attachments/assets/6f736d39-11a9-4be1-8938-d02a7b6a0516)

When using OpenSearch Dashboards Discover, please

- Make sure you're looking at the metrics index
- Verify the time range is set correctly (default is 15 minutes)
- Check the the hits on the right side to ensure the data was present


To learn more about OpenSearch Dashboards, you can refer to the 
[documentation](https://ask.qbusiness.aws.dev/opensearch.org/docs/latest/dashboards/)

**Comment by preethy-1** [comment]
Hi @abhirpat,

Thanks for the response.
![image](https://github.com/user-attachments/assets/63361124-3c39-4025-a537-120f60ea8beb)
Both links are not accessible. Can you please take a look?

**Comment by abhirpat** [comment]
Hi @preethy-1  please try again.
