### ISSUE TITLE
Adding extra static text or buttons on LLM response

### ISSUE THREAD

**Issue by Anjuv25** [aws-solutions/qnabot-on-aws#786]
Hi,

Is there a way, we can add an additional text like, "Do you like the response?" and 2 buttons "Yes" or "No" along with all the LLM responses?

**Comment by fhoueto-amz** [comment]
Hi @Anjuv25 
There is  the thumbs up/down feature, see https://docs.aws.amazon.com/solutions/latest/qnabot-on-aws/tuning-testing-and-troubleshooting-unexpected-answers.html#monitoring-qnabot-on-aws-usage-and-user-feedback and https://docs.aws.amazon.com/solutions/latest/qnabot-on-aws/modifying-configuration-settings.html#configure-words-and-phrases-replacement-in-user-questions
