### ISSUE TITLE
AWS SDK for Javascript version upgrade warning.

### ISSUE THREAD

**Issue by DiljithNair** [aws-solutions/qnabot-on-aws#793]
While we are building the QnABot application, we are presenting with the following warning about AWS SDK for JavaScript version update. It is suggesting upgrading from V2 to V3.

![image](https://github.com/user-attachments/assets/ce1f7f04-651e-4ea6-a79b-23249b300b42)

As we are following the link in the warning "https://a.co/7PzMCcy" and doing the upgrade command below as per docs

`$ npx aws-sdk-js-codemod -t v2-to-v3 ./source`

While we are running the codmod with PATH set to ./source as above we are getting huge set of Transformation errors as below (an excerpt only shown).

![image](https://github.com/user-attachments/assets/61d652cd-407c-41dd-a590-1c45f90d596d)

How can we upgrade QnaBot to use AWS SDK for Javascript V3?

**Comment by fhoueto-amz** [comment]
Thanks for reporting. We will review and revert to you.

**Comment by fhoueto-amz** [comment]
Hi @DiljithNair 
Is this issue related to Lex_Web_Ui? If so, please submit the issue to the github of that component at https://github.com/aws-samples/aws-lex-web-ui

**Comment by michaelin-96** [comment]
Hi @DiljithNair, QnABot has already been migrated to aws-sdk v3 for JavaScript. However the lex-web-ui package we use still has code that is associated with v2 (which is why you are seeing that warning). There is an ongoing effort to remove that in the upcoming release of lex-web-ui. Thanks!
