### ISSUE TITLE
Kibana Dashboard is not displayed on first time launch

### ISSUE THREAD

**Issue by rstrahan** [aws-solutions/qnabot-on-aws#92]
## Expected Behavior

Launching the Kibana dashboard should always display the dashboard

## Actual Behavior

On first launch, it displays the discover / query page instead

![image](https://user-images.githubusercontent.com/10953374/40816302-387ebb4c-651a-11e8-9aa8-0df3f907f2b6.png)

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:
  - Platform:

**Comment by JohnCalhoun** [comment]
problem is how redirect works from the content designer

content designer link to kibana:https://*****.us-east-1.es.amazonaws.com/_plugin/kibana/#/dashboard/Default?_g=()

url you are redirected to if you are not logged in already:https://***.auth.us-east-1.amazoncognito.com/login?response_type=code&client_id=***&redirect_uri=https://***.us-east-1.es.amazonaws.com/_plugin/kibana/app/kibana&state=7a050f95-ee5a-4532-a813-b179487d53ab&scope=openid+email

if you had to login you end up here:https://***.us-east-1.es.amazonaws.com/_plugin/kibana/app/kibana?code=***&state=***#/discover?_g=()&_a=(columns:!(_source),index:qna-dev-dev-master-39,interval:auto,query:'',sort:!(_score,desc))

if you did not have to log in you go here:https://***.us-east-1.es.amazonaws.com/_plugin/kibana/app/kibana#/dashboard/Default?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now%2Fw,mode:quick,to:now%2Fw))&_a=(filters:!(),options:(darkTheme:!f),panels:!((col:9,id:Client-types,panelIndex:3,row:1,size_x:4,size_y:4,type:visualization),(col:1,id:Requests,panelIndex:4,row:1,size_x:8,size_y:4,type:visualization),(col:1,id:Incorrect-feedback-wordcloud,panelIndex:5,row:9,size_x:6,size_y:3,type:visualization),(col:7,id:Correct-feedback-wordcloud,panelIndex:6,row:9,size_x:6,size_y:3,type:visualization),(col:1,id:Logged-Utterances,panelIndex:7,row:5,size_x:12,size_y:4,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'*')),title:Default,uiState:())

so problem is our link path get overriden if we have to login, we could make our own login url for kibana that has the correct redirect, but this would require the user to login/select-sign-in-as everytime they go to kibana.
