### ISSUE TITLE
Add Item card heading font & style inconsistent

### ISSUE THREAD

**Issue by dontirun** [aws-solutions/qnabot-on-aws#99]
<a href="https://github.com/rstrahan"><img src="https://avatars0.githubusercontent.com/u/10953374?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rstrahan](https://github.com/rstrahan)**
_Tuesday May 01, 2018 at 13:03 GMT_
_Originally opened as https://github.com/rstrahan/aws-ai-qna-bot-2/issues/24_

----

## Expected Behavior

Sections and fields in the Add/Update item card should have consistent heading style and font..  

## Actual Behavior

Some are bold, some are grey.. see screenshot.
Or maybe it's that some fields have a heading defined (bold) and some do not.

![image](https://user-images.githubusercontent.com/10953374/39473757-6d7916a8-4d1e-11e8-820b-6c28173363b8.png)

![image](https://user-images.githubusercontent.com/10953374/39473689-fb49f3e0-4d1d-11e8-9430-a11029890a7d.png)

**Comment by JohnCalhoun** [comment]
field order need to be consitant as well
